import { defineEmitter, EmitterError } from "../lib/emitter.mjs";
import { byName, namedTypeRef, printTypeRef, requireType } from "../lib/ir-model.mjs";
import { pascalCase } from "../lib/naming.mjs";

/**
 * C# models, operation descriptors and schema metadata for the ConvoHop .NET
 * SDK in dotnet/. Only the operations of the requested layers (server and both
 * by default) are emitted, with the input, output and enum types they reach.
 * Subscriptions are skipped: the .NET SDK has no realtime transport.
 *
 * - Enums.cs: enums with strict System.Text.Json converters.
 * - Inputs.cs: input classes; required fields are constructor parameters.
 * - Outputs.cs: output classes with init-only properties.
 * - Operations.cs: typed operation descriptors, nested by plane.
 * - ErrorCodes.cs: the stable error codes.
 * - Schema.cs: output shapes and scalar constraints for response validation.
 * - JsonContext.cs: the System.Text.Json source-generation context.
 * - Apis.cs: one class per plane with a method per operation, and an
 *   IAsyncEnumerable pages method per cursor-paginated query.
 */
export const DEFAULT_DIRECTORY = "dotnet/src/ConvoHop/Generated";
export const DEFAULT_LAYERS = Object.freeze(["server", "both"]);

const LAYERS = new Set(["client", "server", "both"]);
const KINDS = { query: "Query", mutation: "Mutation" };
const NOTICE = "// <auto-generated>\n// Generated from the current unversioned GraphQL schemas. Run npm run generate:graphql.\n// </auto-generated>\n#nullable enable\n";
const JSON_ELEMENT = "global::System.Text.Json.JsonElement";
const READ_ONLY_LIST = "global::System.Collections.Generic.IReadOnlyList";
const SERIALIZATION = "global::System.Text.Json.Serialization";
const REPRESENTATION_TYPES = {
  string: { type: "string", value: false },
  integer: { type: "int", value: true },
  number: { type: "double", value: true },
  boolean: { type: "bool", value: true },
  object: { type: JSON_ELEMENT, value: true },
};
const INT32_MIN = -(2 ** 31);
const INT32_MAX = 2 ** 31 - 1;
// graphql-js prints `@deprecated` without a reason as this default.
const DEFAULT_DEPRECATION_REASON = "No longer supported";
const IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;
const RESERVED_MEMBERS = new Set(["Equals", "Finalize", "GetHashCode", "GetType", "MemberwiseClone", "ReferenceEquals", "ToString"]);
const KEYWORDS = new Set(`abstract as base bool break byte case catch char checked class const continue decimal default delegate do
double else enum event explicit extern false finally fixed float for foreach goto if implicit in int interface internal is lock long
namespace new null object operator out override params private protected public readonly ref return sbyte sealed short sizeof
stackalloc static string struct switch this throw true try typeof uint ulong unchecked unsafe ushort using virtual void volatile while`.split(/\s+/));

const escapeIdentifier = name => (KEYWORDS.has(name) ? `@${name}` : name);

/** A C# string literal. JSON escapes are valid C#, except that C# also treats U+0085, U+2028 and U+2029 as line breaks. */
export function csString(text) {
  return JSON.stringify(text).replace(/[\u0085\u2028\u2029]/g, char => `\\u${char.charCodeAt(0).toString(16).padStart(4, "0")}`);
}

/**
 * A schema pattern (ECMAScript) as a .NET regular expression that accepts the same strings. Only the subset where the
 * two agree after translation is accepted: `$` becomes `\z` (a .NET `$` also matches before a final newline) and `\d`
 * becomes `[0-9]` (a .NET `\d` matches every Unicode digit). Other constructs (`.`, `(?` groups, other escapes,
 * nested classes and non-ASCII text) are rejected rather than translated.
 */
export function csPattern(pattern) {
  const unsupported = detail => new EmitterError(`csharp: scalar pattern ${JSON.stringify(pattern)} uses ${detail}, which the C# emitter does not translate`);
  let out = "";
  let inClass = false;
  for (let index = 0; index < pattern.length; index++) {
    const char = pattern[index];
    if (char === "\\") {
      const next = pattern[index + 1];
      if (next === undefined || !/^[\\^$.|?*+()[\]{}/dD-]$/.test(next)) throw unsupported(`the escape \\${next ?? ""}`);
      if (next === "D" && inClass) throw unsupported("\\D inside a character class");
      out += next === "d" ? (inClass ? "0-9" : "[0-9]") : next === "D" ? "[^0-9]" : char + next;
      index++;
    } else if (inClass) {
      if (char === "[") throw unsupported("[ inside a character class");
      if (!/^[ -~]$/.test(char)) throw unsupported("non-ASCII text");
      if (char === "]") inClass = false;
      out += char;
    } else if (char === "[") {
      if (pattern[index + 1] === "]") throw unsupported("an empty character class");
      inClass = true;
      out += char;
    } else if (char === "$") {
      out += "\\z";
    } else if (char === "." || (char === "(" && pattern[index + 1] === "?")) {
      throw unsupported(char === "." ? "." : "a (? group");
    } else if (!/^[A-Za-z0-9^|()?*+{},:_ -]$/.test(char)) {
      throw unsupported(JSON.stringify(char));
    } else {
      out += char;
    }
  }
  if (inClass) throw unsupported("an unterminated character class");
  return out;
}

/**
 * The C# type of a scalar. Integers are `int`, which the runtime validates as 32-bit, so a custom integer scalar needs a
 * minimum and maximum within 32 bits.
 */
export function scalarType(type) {
  const mapped = REPRESENTATION_TYPES[type.representation];
  if (!mapped) throw new EmitterError(`csharp: scalar ${type.name} has unsupported representation ${JSON.stringify(type.representation)}`);
  if (type.representation === "integer" && !type.builtIn) {
    const fits = value => Number.isInteger(value) && value >= INT32_MIN && value <= INT32_MAX;
    const { minimum, maximum } = type.constraints ?? {};
    if (!fits(minimum) || !fits(maximum)) {
      throw new EmitterError(`csharp: integer scalar ${type.name} needs a minimum and maximum within 32 bits; extend the emitter for wider integers`);
    }
  }
  return mapped;
}

const xmlText = text => text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/** An XML doc comment for schema text, which is escaped. */
function docComment(text, pad, tag = "summary") {
  return docXml(xmlText(text), pad, tag);
}

/** An XML doc comment for markup the emitter wrote. */
function docXml(xml, pad, tag = "summary") {
  const lines = xml.split("\n");
  if (lines.length === 1) return `${pad}/// <${tag}>${lines[0]}</${tag}>\n`;
  return [`<${tag}>`, ...lines, `</${tag}>`].map(line => `${pad}/// ${line}`.trimEnd()).join("\n") + "\n";
}

function obsolete(deprecated, pad) {
  if (!deprecated) return "";
  return `${pad}[global::System.Obsolete(${csString(deprecated.reason ?? DEFAULT_DEPRECATION_REASON)})]\n`;
}

/** The PascalCase C# member name for a GraphQL field, enum value or error code. */
export function memberName(name, where) {
  const member = pascalCase(name);
  if (!IDENTIFIER.test(member)) throw new EmitterError(`csharp: ${where}: cannot derive a C# member name from ${JSON.stringify(name)}`);
  return member;
}

function uniqueMembers(entries, owner, where) {
  const seen = new Map();
  for (const [source, member] of entries) {
    if (member === owner) throw new EmitterError(`csharp: ${where}: ${JSON.stringify(source)} maps to ${member}, the name of its enclosing type`);
    if (RESERVED_MEMBERS.has(member)) throw new EmitterError(`csharp: ${where}: ${JSON.stringify(source)} maps to ${member}, which would hide System.Object.${member}`);
    if (seen.has(member)) throw new EmitterError(`csharp: ${where}: ${JSON.stringify(seen.get(member))} and ${JSON.stringify(source)} both map to ${member}`);
    seen.set(member, source);
  }
}

function modelName(name) {
  if (!IDENTIFIER.test(name)) throw new EmitterError(`csharp: type name ${JSON.stringify(name)} is not a C# identifier`);
  return escapeIdentifier(name);
}

/** The C# type of an IR type reference. Model types are named relative to the ConvoHop.Models namespace unless `qualified`. */
export function csType(ref, types, where, qualified = false) {
  if (ref.kind === "list") {
    const list = `${READ_ONLY_LIST}<${csType(ref.ofType, types, where, qualified)}>`;
    return ref.nullable ? `${list}?` : list;
  }
  const type = requireType(types, ref.name, where);
  let name;
  if (type.kind === "scalar") {
    name = scalarType(type).type;
  } else if (["enum", "object", "input"].includes(type.kind)) {
    name = qualified ? `global::ConvoHop.Models.${modelName(type.name)}` : modelName(type.name);
  } else {
    throw new EmitterError(`csharp: ${where}: unsupported type kind ${JSON.stringify(type.kind)}`);
  }
  return ref.nullable ? `${name}?` : name;
}

/** The emitted operations, in IR order, and the input, output and enum types they reach, in IR type order. */
export function selectOperations(ir, layers) {
  const types = byName(ir.types);
  const operations = ir.operations.filter(operation => layers.includes(operation.layer) && Object.hasOwn(KINDS, operation.kind));
  const reached = new Set();
  const visit = (name, direction, where) => {
    const type = requireType(types, name, where);
    if (type.kind === "object" || type.kind === "input") {
      const expected = direction === "input" ? "input" : "object";
      if (type.kind !== expected) throw new EmitterError(`csharp: ${where}: ${direction} position references ${type.kind} type ${name}`);
      if (reached.has(name)) return;
      reached.add(name);
      for (const field of type.fields) visit(namedTypeRef(field.type).name, direction, `${name}.${field.name}`);
    } else {
      reached.add(name);
    }
  };
  for (const operation of operations) {
    visit(namedTypeRef(operation.result.type).name, "output", operation.id);
    if (operation.input) visit(operation.input.type, "input", operation.id);
  }
  return { types, operations, reached: ir.types.filter(type => reached.has(type.name)) };
}

function file(directory, name, namespace, body, header = "") {
  return { path: `${directory}/${name}`, contents: `${NOTICE}${header}\nnamespace ${namespace}\n{\n${body.join("\n")}}\n` };
}

function renderEnums(enums) {
  const body = [];
  for (const type of enums) {
    const members = type.values.map(value => [value.name, memberName(value.name, `${type.name}.${value.name}`)]);
    uniqueMembers(members, type.name, type.name);
    const name = modelName(type.name);
    let text = docComment(type.description ?? `The ${type.name} enum.`, "    ");
    text += `    [${SERIALIZATION}.JsonConverter(typeof(global::ConvoHop.Generated.EnumConverters.${type.name}Converter))]\n`;
    text += `    public enum ${name}\n    {\n`;
    text += type.values.map((value, index) => (value.description ? docComment(value.description, "        ") : docXml(`The <c>${value.name}</c> value.`, "        "))
      + obsolete(value.deprecated, "        ") + `        ${members[index][1]},\n`).join("");
    body.push(`${text}    }\n`);
  }
  return body;
}

function renderEnumConverters(enums) {
  const converters = enums.map(type => {
    const name = `global::ConvoHop.Models.${modelName(type.name)}`;
    const members = type.values.map(value => [value.name, memberName(value.name, `${type.name}.${value.name}`)]);
    return `        internal sealed class ${type.name}Converter : ${SERIALIZATION}.JsonConverter<${name}>
        {
            public override ${name} Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
            {
                if (reader.TokenType == global::System.Text.Json.JsonTokenType.String)
                {
                    switch (reader.GetString())
                    {
${members.map(([wire, member]) => `                        case ${csString(wire)}: return ${name}.${member};\n`).join("")}                    }
                }
                throw new global::System.Text.Json.JsonException(${csString(`Unknown ${type.name} value`)});
            }

            public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ${name} value, global::System.Text.Json.JsonSerializerOptions options)
            {
                writer.WriteStringValue(ToWire(value));
            }

            internal static string ToWire(${name} value)
            {
                switch (value)
                {
${members.map(([wire, member]) => `                    case ${name}.${member}: return ${csString(wire)};\n`).join("")}                    default: throw new global::System.ArgumentOutOfRangeException(nameof(value), ${csString(`Unknown ${type.name} value`)});
                }
            }
        }
`;
  });
  return [`    internal static class EnumConverters\n    {\n${converters.join("\n")}    }\n`];
}

function propertyMembers(type) {
  const members = type.fields.map(field => [field.name, memberName(field.name, `${type.name}.${field.name}`)]);
  uniqueMembers(members, type.name, type.name);
  return members;
}

function renderInputs(inputs, types) {
  return inputs.map(type => {
    const name = modelName(type.name);
    const members = propertyMembers(type);
    const fields = type.fields.map((field, index) => ({
      field, member: members[index][1], cs: csType(field.type, types, `${type.name}.${field.name}`),
      required: !field.type.nullable && !Object.hasOwn(field, "defaultValue"),
    }));
    const required = fields.filter(entry => entry.required);
    const parameters = required.map(entry => `${entry.cs} ${escapeIdentifier(entry.field.name)}`).join(", ");
    let text = docComment(type.description ?? `The ${type.name} input.`, "    ");
    text += `    public sealed class ${name}\n    {\n`;
    text += required.length ? "        /// <summary>Creates the input from its required fields.</summary>\n" : "        /// <summary>Creates the input.</summary>\n";
    for (const entry of required) text += `        /// <param name="${entry.field.name}">The <c>${entry.field.name}</c> field.</param>\n`;
    text += `        public ${name}(${parameters})\n        {\n`;
    text += required.map(entry => `            this.${entry.member} = ${escapeIdentifier(entry.field.name)};\n`).join("");
    text += "        }\n";
    for (const entry of fields) {
      const optional = entry.required ? "" : entry.cs.endsWith("?") ? entry.cs : `${entry.cs}?`;
      text += "\n" + (entry.field.description ? docComment(entry.field.description, "        ") : docXml(`The <c>${entry.field.name}</c> field.`, "        "));
      if (Object.hasOwn(entry.field, "defaultValue")) {
        text += `        /// <remarks>Omitted when null; the authority then applies the default <c>${xmlText(JSON.stringify(entry.field.defaultValue))}</c>.</remarks>\n`;
      } else if (!entry.required) {
        text += "        /// <remarks>Omitted when null.</remarks>\n";
      }
      text += obsolete(entry.field.deprecated, "        ");
      text += `        [${SERIALIZATION}.JsonPropertyName(${csString(entry.field.name)})]\n`;
      if (!entry.required) text += `        [${SERIALIZATION}.JsonIgnore(Condition = ${SERIALIZATION}.JsonIgnoreCondition.WhenWritingNull)]\n`;
      text += `        public ${entry.required ? entry.cs : optional} ${entry.member} { get; set; }\n`;
    }
    return `${text}    }\n`;
  });
}

function renderOutputs(outputs, types) {
  return outputs.map(type => {
    const name = modelName(type.name);
    const members = propertyMembers(type);
    let text = docComment(type.description ?? `The ${type.name} result.`, "    ");
    text += `    public sealed class ${name}\n    {\n`;
    text += type.fields.map((field, index) => {
      const cs = csType(field.type, types, `${type.name}.${field.name}`);
      const initializer = field.type.nullable || isValueType(field.type, types, type.name) ? "" : " = default!;";
      return (field.description ? docComment(field.description, "        ") : docXml(`The <c>${field.name}</c> field.`, "        "))
        + obsolete(field.deprecated, "        ")
        + `        [${SERIALIZATION}.JsonPropertyName(${csString(field.name)})]\n`
        + `        public ${cs} ${members[index][1]} { get; init; }${initializer}\n`;
    }).join("\n");
    return `${text}    }\n`;
  });
}

function descriptorTypes(operation, types) {
  const input = operation.input
    ? csType({ kind: "input", name: operation.input.type, nullable: !operation.input.required }, types, operation.id, true)
    : "global::ConvoHop.NoInput";
  return { input, result: csType(operation.result.type, types, operation.id, true) };
}

function renderOperations(ir, operations, types) {
  const planes = [...new Set(operations.map(operation => operation.plane))];
  const planeMembers = planes.map(plane => [plane, memberName(plane, `plane ${plane}`)]);
  uniqueMembers([...planeMembers, ["(all operations)", "All"]], "Operations", "Operations");
  const lines = [];
  const all = [];
  for (const [plane, planeClass] of planeMembers) {
    const summary = ir.planes.find(entry => entry.name === plane)?.summary ?? `The ${plane} plane.`;
    const members = operations.filter(operation => operation.plane === plane).map(operation => [operation.field, memberName(operation.field, operation.id), operation]);
    uniqueMembers(members, planeClass, `plane ${plane}`);
    const body = members.map(([, member, operation]) => {
      const { input, result } = descriptorTypes(operation, types);
      const inputFields = operation.input ? requireType(types, operation.input.type, operation.id).fields.map(field => field.name) : [];
      all.push(`${planeClass}.${member}`);
      return docComment(operation.summary ?? operation.id, "            ")
        + obsolete(operation.deprecated, "            ")
        + `            public static readonly global::ConvoHop.OperationDescriptor<${input}, ${result}> ${member} = new global::ConvoHop.OperationDescriptor<${input}, ${result}>(\n`
        + [
          `id: ${csString(operation.id)}`,
          `plane: ${csString(operation.plane)}`,
          `kind: global::ConvoHop.OperationKind.${KINDS[operation.kind]}`,
          `field: ${csString(operation.field)}`,
          `operationName: ${csString(operation.operationName)}`,
          `document: ${csString(operation.document.text)}`,
          `resultType: ${csString(printTypeRef(operation.result.type))}`,
          `contextArgument: ${csString(operation.context.argument)}`,
          `inputArgument: ${operation.input ? csString(operation.input.argument) : "null"}`,
          `inputRequired: ${operation.input ? String(operation.input.required) : "false"}`,
          `inputFields: ${inputFields.length ? `new string[] { ${inputFields.map(csString).join(", ")} }` : "global::System.Array.Empty<string>()"}`,
          `contextFields: new global::ConvoHop.ContextField[]\n                {\n${operation.context.fields.map(field =>
            `                    new global::ConvoHop.ContextField(${csString(field.name)}, global::ConvoHop.ContextFieldUse.${memberName(field.use, `${operation.id} context use`)}),\n`).join("")}                }`,
          `idempotency: ${csString(operation.idempotency)}`,
          `layer: ${csString(operation.layer)}`,
          `pagination: ${csString(operation.pagination?.style ?? "none")}`,
        ].map(argument => `                ${argument}`).join(",\n")
        + ");\n";
    });
    lines.push(docComment(summary, "        ") + `        public static class ${planeClass}\n        {\n${body.join("\n")}        }\n`);
  }
  const resolvers = ir.planes.filter(plane => plane.resolveOperation && planes.includes(plane.name)).map(plane => {
    const operation = operations.find(entry => entry.id === plane.resolveOperation);
    if (!operation) throw new EmitterError(`csharp: plane ${plane.name} resolves requests with ${plane.resolveOperation}, which is not emitted`);
    return `                case ${csString(plane.name)}: return ${memberName(plane.name, plane.name)}.${memberName(operation.field, operation.id)};\n`;
  });
  lines.push(`        /// <summary>Every operation descriptor, in schema order.</summary>
        public static readonly ${READ_ONLY_LIST}<global::ConvoHop.OperationDescriptor> All = new global::ConvoHop.OperationDescriptor[]
        {
${all.map(entry => `            ${entry},\n`).join("")}        };

        /// <summary>The operation that resolves a request ID on a plane, or null when the plane has none.</summary>
        /// <param name="plane">The plane name.</param>
        public static global::ConvoHop.OperationDescriptor? ResolveOperation(string plane)
        {
            switch (plane)
            {
${resolvers.join("")}                default: return null;
            }
        }
`);
  return [`    /// <summary>Descriptors of the generated GraphQL operations.</summary>\n    public static class Operations\n    {\n${lines.join("\n")}    }\n`];
}

function renderErrorCodes(ir) {
  const codes = ir.errors.codes.map(code => [code.name, memberName(code.name, `error code ${code.name}`), code]);
  uniqueMembers(codes, "ErrorCodes", "ErrorCodes");
  const body = codes.map(([wire, member, code]) => docComment(code.summary, "        ")
    + `        public const string ${member} = ${csString(wire)};\n`).join("\n");
  return [`    /// <summary>Stable machine-readable error codes. Classify errors by code, never by message text.</summary>\n    public static class ErrorCodes\n    {\n${body}    }\n`];
}

function scalarShape(type) {
  const constraints = type.constraints ?? {};
  const known = new Set(["pattern", "disallowed", "maximumDecimal", "minimum", "maximum", "maxCanonicalJsonBytes", "requiredStringProperties"]);
  for (const key of Object.keys(constraints)) {
    if (!known.has(key)) throw new EmitterError(`csharp: scalar ${type.name} has unsupported constraint ${JSON.stringify(key)}`);
  }
  scalarType(type);
  const number = value => (Number.isFinite(value) ? `${String(value)}d` : (() => { throw new EmitterError(`csharp: scalar ${type.name} has a non-finite bound`); })());
  const strings = values => `new string[] { ${values.map(csString).join(", ")} }`;
  const args = [csString(type.representation)];
  if (constraints.pattern !== undefined) args.push(`pattern: ${csString(csPattern(constraints.pattern))}`);
  if (constraints.disallowed !== undefined) args.push(`disallowed: ${strings(constraints.disallowed)}`);
  if (constraints.maximumDecimal !== undefined) args.push(`maximumDecimal: ${csString(constraints.maximumDecimal)}`);
  if (constraints.minimum !== undefined) args.push(`minimum: ${number(constraints.minimum)}`);
  if (constraints.maximum !== undefined) args.push(`maximum: ${number(constraints.maximum)}`);
  if (constraints.maxCanonicalJsonBytes !== undefined) {
    const bytes = constraints.maxCanonicalJsonBytes;
    if (!Number.isInteger(bytes) || bytes < 1 || bytes > INT32_MAX) throw new EmitterError(`csharp: scalar ${type.name} has an invalid maxCanonicalJsonBytes`);
    args.push(`maxCanonicalJsonBytes: ${bytes}`);
  }
  if (constraints.requiredStringProperties !== undefined) args.push(`requiredStringProperties: ${strings(constraints.requiredStringProperties)}`);
  return `global::ConvoHop.Internal.TypeShape.Scalar(${args.join(", ")})`;
}

function renderSchema(reached) {
  const shapes = reached.filter(type => type.kind !== "input").map(type => {
    let shape;
    if (type.kind === "object") {
      shape = `global::ConvoHop.Internal.TypeShape.Object(new global::ConvoHop.Internal.FieldShape[]\n                {\n${type.fields.map(field =>
        `                    new global::ConvoHop.Internal.FieldShape(${csString(field.name)}, ${csString(printTypeRef(field.type))}),\n`).join("")}                })`;
    } else if (type.kind === "enum") {
      shape = `global::ConvoHop.Internal.TypeShape.Enum(new string[] { ${type.values.map(value => csString(value.name)).join(", ")} })`;
    } else {
      shape = scalarShape(type);
    }
    return `            [${csString(type.name)}] = ${shape},\n`;
  });
  return [`    internal static class GeneratedSchema
    {
        /// <summary>Output shapes keyed by GraphQL type name: objects, enums and scalars.</summary>
        internal static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::ConvoHop.Internal.TypeShape> Types =
            new global::System.Collections.Generic.Dictionary<string, global::ConvoHop.Internal.TypeShape>(global::System.StringComparer.Ordinal)
        {
${shapes.join("")}        };
    }
`];
}

/** A C# type usable in typeof(): value types keep their nullability, reference types drop the annotation. */
function serializableType(ref, types, where) {
  if (ref.kind === "list") return `${READ_ONLY_LIST}<${serializableType(ref.ofType, types, where)}>`;
  const name = csType({ ...ref, nullable: false }, types, where, true);
  return ref.nullable && isValueType(ref, types, where) ? `${name}?` : name;
}

function isValueType(ref, types, where) {
  if (ref.kind === "list") return false;
  const type = requireType(types, ref.name, where);
  return type.kind === "enum" || (type.kind === "scalar" && scalarType(type).value);
}

function renderJsonContext(operations, reached, types) {
  const serializable = new Set();
  for (const type of reached) {
    if (type.kind === "object" || type.kind === "input") serializable.add(`global::ConvoHop.Models.${modelName(type.name)}`);
  }
  for (const operation of operations) serializable.add(serializableType(operation.result.type, types, operation.id));
  return [`    [${SERIALIZATION}.JsonSourceGenerationOptions(GenerationMode = ${SERIALIZATION}.JsonSourceGenerationMode.Metadata)]
${[...serializable].map(cs => `    [${SERIALIZATION}.JsonSerializable(typeof(${cs}))]\n`).join("")}    internal sealed partial class ConvoHopJsonContext : ${SERIALIZATION}.JsonSerializerContext
    {
    }
`];
}

// The idempotency retry rules the generated plane APIs understand.
const RETRY = new Set(["repeat", "sameRequest", "none"]);
// How PageSequence checks that each next cursor advances: ordered styles compare decimal cursors, other cursors must change.
const PAGE_ORDER = { server: "Opaque", ascending: "Ascending", descending: "Descending" };
const PAGE_FIELDS = ["complete", "refreshRequired", "nextCursor"];
// The parameter names a plane API method may declare besides a context credential.
const API_PARAMETERS = new Set(["input", "requestId", "cancellationToken"]);
// A documentation ID: the compiler copies it unchecked, so the edge compile check needs no ConvoHopException.
const EXCEPTION_CREF = "T:ConvoHop.ConvoHopException";
const TASK = "global::System.Threading.Tasks.Task";
const CANCELLATION_TOKEN = "global::System.Threading.CancellationToken";

/** Per-operation facts for the plane APIs: the idempotency policy, any context credential and any pages method. */
function describeApis(ir, operations, types) {
  const idempotency = byName(ir.idempotency);
  const credentials = byName(ir.credentials);
  const planes = byName(ir.planes);
  const styles = byName(ir.pagination);
  return operations.map(operation => {
    const where = `csharp: ${operation.id}`;
    const policy = idempotency.get(operation.idempotency);
    if (!policy || !RETRY.has(policy.retry)) throw new EmitterError(`${where} has unsupported idempotency ${JSON.stringify(operation.idempotency)}`);
    const plane = planes.get(operation.plane);
    if (!plane) throw new EmitterError(`${where} names unknown plane ${operation.plane}`);
    const carriers = operation.auth.map(entry => credentials.get(entry.credential)).filter(credential => credential?.carrier === "context");
    if (carriers.length > 1) throw new EmitterError(`${where} accepts several context credentials`);
    let permit = null;
    if (carriers.length) {
      const contextType = requireType(types, plane.context.type, where);
      const field = contextType.fields.find(entry => entry.name === carriers[0].contextField);
      if (!field) throw new EmitterError(`${where}: ${plane.context.type} has no ${carriers[0].contextField} field`);
      if (field.type.kind !== "scalar") throw new EmitterError(`${where}: context credential ${field.name} is not a scalar; extend the emitter`);
      if (!IDENTIFIER.test(field.name) || API_PARAMETERS.has(field.name)) {
        throw new EmitterError(`${where}: context credential ${JSON.stringify(field.name)} cannot be a C# parameter name`);
      }
      // The executor takes the credential as an object; the transport sends JSON object credentials only.
      const { type, value } = scalarType(requireType(types, field.type.name, where));
      permit = { field: field.name, parameter: escapeIdentifier(field.name), type, check: type === JSON_ELEMENT ? "default" : value ? null : "null" };
    }
    const input = operation.input ? requireType(types, operation.input.type, where) : null;
    return {
      operation, policy, permit, input,
      planeClass: memberName(operation.plane, `plane ${operation.plane}`),
      member: memberName(operation.field, operation.id),
      inputRequired: Boolean(operation.input?.required),
      requestId: operation.kind === "mutation" && policy.retry === "sameRequest",
      pages: describePages(styles, types, operation, input, permit, where),
    };
  });
}

/**
 * The pages method of a query whose pagination style takes a cursor input, or null. PageSequence sends the input, then
 * the input with the cursor field set to each page's nextCursor until a page is complete. Ordered styles with a decimal
 * cursor check the cursor moves in that order; other cursors must change.
 */
function describePages(styles, types, operation, input, permit, where) {
  const pagination = operation.pagination;
  if (!pagination) return null;
  const style = styles.get(pagination.style);
  if (!style) throw new EmitterError(`${where} names unknown pagination style ${JSON.stringify(pagination.style)}`);
  if (!style.cursorInput) return null;
  const invalid = detail => new EmitterError(`${where}: ${detail}`);
  const unsupported = detail => invalid(`${detail}; extend the emitter`);
  if (operation.kind !== "query") throw unsupported(`${style.name} pagination of a ${operation.kind}`);
  if (permit) throw unsupported(`${style.name} pagination with a context credential`);
  const order = PAGE_ORDER[style.order];
  if (!order) throw unsupported(`pagination style ${style.name} has order ${JSON.stringify(style.order)}`);
  const missing = PAGE_FIELDS.filter(name => !style.pageFields.includes(name));
  if (missing.length) throw unsupported(`pagination style ${style.name} has no ${missing.join(", ")} page field`);
  const cursorField = input?.fields.find(field => field.name === pagination.cursorField);
  if (!cursorField || cursorField.type.kind !== "scalar" || !cursorField.type.nullable) {
    throw invalid(`the cursor input ${input?.name ?? "(none)"}.${pagination.cursorField} is not an optional scalar field`);
  }
  const cursorScalar = requireType(types, cursorField.type.name, where);
  if (cursorScalar.representation !== "string") throw unsupported(`the cursor input ${input.name}.${pagination.cursorField} is not a string scalar`);
  const result = operation.result.type;
  if (result.kind !== "object") throw invalid("the paginated result is not an object");
  if (pagination.pagePath.length > 1) throw unsupported(`pagePath ${pagination.pagePath.join(".")} is deeper than one field`);
  let page = requireType(types, result.name, where);
  let accessor = "reply => reply";
  for (const segment of pagination.pagePath) {
    const field = page.fields.find(entry => entry.name === segment);
    if (!field || field.type.kind !== "object") throw invalid(`pagePath field ${page.name}.${segment} is not an object field`);
    accessor = `reply => reply${result.nullable ? "?" : ""}.${memberName(segment, `${page.name}.${segment}`)}`;
    page = requireType(types, field.type.name, where);
  }
  if (page.name !== pagination.pageType) throw invalid(`pagePath reaches ${page.name}, not the page type ${pagination.pageType}`);
  const pageField = name => page.fields.find(field => field.name === name)?.type;
  const flag = ref => ref?.kind === "scalar" && ref.name === "Boolean" && !ref.nullable;
  const next = pageField("nextCursor");
  if (!flag(pageField("complete")) || !flag(pageField("refreshRequired")) || next?.kind !== "scalar"
      || requireType(types, next.name, where).representation !== "string") {
    throw invalid(`${page.name} needs complete: Boolean!, refreshRequired: Boolean! and a string nextCursor`);
  }
  const decimal = cursorScalar.constraints?.maximumDecimal !== undefined;
  return {
    method: `${memberName(operation.field, operation.id)}PagesAsync`,
    style,
    page,
    accessor,
    cursorField: pagination.cursorField,
    cursorScalar: cursorScalar.name,
    order: decimal ? order : "Opaque",
  };
}

function authorization(operation) {
  return operation.auth.map(entry => {
    const details = [
      ...(entry.scopes?.length ? [`scopes ${entry.scopes.join(", ")}`] : []),
      ...(entry.condition ? [`condition ${entry.condition}`] : []),
    ];
    return `${entry.credential}${details.length ? ` (${details.join("; ")})` : ""}`;
  }).join(", ");
}

const paragraphs = texts => texts.filter(Boolean).map(text => `<para>${text}</para>`).join("\n");

function renderApiMethod(entry, types) {
  const { operation, policy, permit, input, inputRequired, requestId, planeClass, member } = entry;
  const { input: inputType, result } = descriptorTypes(operation, types);
  const pad = "        ";
  const parameters = [];
  const params = [];
  if (input) {
    // A default would have to precede the required credential parameter.
    parameters.push(`${inputType} input${inputRequired || permit ? "" : " = null"}`);
    params.push(["input", inputRequired ? "The operation input." : "The operation input, or null to send an empty input."]);
  }
  if (permit) {
    parameters.push(`${permit.type} ${permit.parameter}`);
    params.push([permit.field, `The <c>${permit.field}</c> credential, sent unchanged in the request context.`]);
  }
  if (requestId) {
    parameters.push("string? requestId = null");
    params.push(["requestId", "The request ID of an earlier attempt to retry with the same input, or null for a new one."]);
  }
  parameters.push(`${CANCELLATION_TOKEN} cancellationToken = default`);
  params.push(["cancellationToken", operation.kind === "mutation" ? "Stops waiting. A cancelled mutation has an unknown outcome." : "Stops waiting."]);
  const remarks = paragraphs([
    operation.description && xmlText(operation.description),
    `Idempotency: <c>${xmlText(policy.name)}</c>.${policy.summary ? ` ${xmlText(policy.summary)}` : ""}`,
    operation.auth.length && `Authorization: ${xmlText(authorization(operation))}.`,
    operation.destructive && "Destructive: it deletes, revokes, removes, disables or ends something.",
  ]);
  let text = docComment(operation.summary ?? operation.id, pad);
  if (remarks) text += docXml(remarks, pad, "remarks");
  text += params.map(([name, doc]) => `${pad}/// <param name="${name}">${doc}</param>\n`).join("");
  text += `${pad}/// <returns>The authority result.</returns>\n`;
  const nulls = [...(input && inputRequired ? ["input"] : []), ...(permit?.check === "null" ? [permit.field] : [])];
  if (nulls.length) {
    text += `${pad}/// <exception cref="System.ArgumentNullException">${nulls.map(name => `<paramref name="${name}"/>`).join(" or ")} is null.</exception>\n`;
  }
  if (permit?.check === "default") {
    text += `${pad}/// <exception cref="System.ArgumentException"><paramref name="${permit.field}"/> is a default <see cref="System.Text.Json.JsonElement"/>.</exception>\n`;
  }
  text += `${pad}/// <exception cref="${EXCEPTION_CREF}">The request was invalid, the authority rejected it, or its outcome is unknown.</exception>\n`;
  text += obsolete(operation.deprecated, pad);
  const check = (input && inputRequired ? `${pad}    if (input is null) throw new global::System.ArgumentNullException(nameof(input));\n` : "")
    + (permit?.check === "null" ? `${pad}    if (${permit.parameter} is null) throw new global::System.ArgumentNullException(nameof(${permit.parameter}));\n` : "")
    + (permit?.check === "default" ? `${pad}    if (${permit.parameter}.ValueKind == global::System.Text.Json.JsonValueKind.Undefined) `
      + `throw new global::System.ArgumentException("Expected a credential, not a default JsonElement", nameof(${permit.parameter}));\n` : "");
  const call = `_executor.ExecuteAsync(global::ConvoHop.Operations.${planeClass}.${member}, ${input ? "input" : "global::ConvoHop.NoInput.Value"}, `
    + `${requestId ? "requestId" : "null"}, ${permit ? permit.parameter : "null"}, cancellationToken)`;
  return `${text}${pad}public ${TASK}<${result}> ${member}Async(${parameters.join(", ")})\n${pad}{\n${check}${pad}    return ${call};\n${pad}}\n`;
}

function renderPagesMethod(entry, types) {
  const { operation, inputRequired, planeClass, member, pages } = entry;
  const { input: inputType, result } = descriptorTypes(operation, types);
  const page = `global::ConvoHop.Models.${modelName(pages.page.name)}`;
  const pad = "        ";
  const remarks = paragraphs([
    `Each page is requested when enumeration reaches it. Later requests set <c>${pages.cursorField}</c> to the previous page's <c>nextCursor</c>, and enumeration ends after the page whose <c>complete</c> is true. Each enumeration starts again from the input as it was when this method was called, and every request has a new request ID.`,
    `Pagination: <c>${xmlText(pages.style.name)}</c>.${pages.style.summary ? ` ${xmlText(pages.style.summary)}` : ""}`,
    `Enumeration throws <see cref="${EXCEPTION_CREF}"/> if the authority rejects a request or a page is malformed or does not advance, and <see cref="System.InvalidOperationException"/> if a page reports <c>refreshRequired</c>: start again from current state, not from the cursor. These page failures are final. After any other failed request, an enumerator can call <c>MoveNextAsync</c> again to repeat it; <c>await foreach</c> stops at the first exception.`,
  ]);
  let text = docXml(`The pages of <see cref="${member}Async"/>, requested lazily.`, pad);
  text += docXml(remarks, pad, "remarks");
  text += `${pad}/// <param name="input">The first page's input${inputRequired ? "" : ", or null to send an empty input"}.</param>\n`;
  text += `${pad}/// <param name="cancellationToken">Stops waiting for a page, together with any token passed to <c>WithCancellation</c>.</param>\n`;
  text += `${pad}/// <returns>The pages, in order.</returns>\n`;
  if (inputRequired) text += `${pad}/// <exception cref="System.ArgumentNullException"><paramref name="input"/> is null.</exception>\n`;
  text += `${pad}/// <exception cref="System.ArgumentException">The input's <c>${pages.cursorField}</c> is not a valid cursor.</exception>\n`;
  text += obsolete(operation.deprecated, pad);
  const field = name => memberName(name, `${pages.page.name}.${name}`);
  const pageMember = name => `page => page.${field(name)}`;
  return `${text}${pad}public global::System.Collections.Generic.IAsyncEnumerable<${page}> ${pages.method}(${inputType} input${inputRequired ? "" : " = null"}, ${CANCELLATION_TOKEN} cancellationToken = default)
${pad}{
${pad}    return global::ConvoHop.Internal.PageSequence.Create<${inputType}, ${result}, ${page}>(
${pad}        _executor, global::ConvoHop.Operations.${planeClass}.${member}, input, ${csString(pages.cursorField)},
${pad}        global::ConvoHop.Generated.GeneratedSchema.Types[${csString(pages.cursorScalar)}], global::ConvoHop.Internal.PageOrder.${pages.order},
${pad}        ${pages.accessor}, ${pageMember("complete")}, ${pageMember("refreshRequired")}, ${pageMember("nextCursor")},
${pad}        cancellationToken);
${pad}}
`;
}

function renderApis(ir, described, types) {
  const planes = [...new Set(described.map(entry => entry.operation.plane))];
  return planes.map(name => {
    const plane = ir.planes.find(entry => entry.name === name);
    const entries = described.filter(entry => entry.operation.plane === name);
    const className = `${entries[0].planeClass}Api`;
    uniqueMembers(entries.flatMap(entry => [
      [entry.operation.field, `${entry.member}Async`],
      ...(entry.pages ? [[`${entry.operation.field} pages`, entry.pages.method]] : []),
    ]), className, className);
    const methods = entries.flatMap(entry => [renderApiMethod(entry, types), ...(entry.pages ? [renderPagesMethod(entry, types)] : [])]);
    return docXml(`The <c>${xmlText(name)}</c> plane: ${xmlText(plane.summary ?? `the ${name} operations.`)}`, "    ")
      + "    /// <remarks>Obtain an instance from a client. Instances are thread-safe.</remarks>\n"
      + `    public sealed class ${className}\n    {\n`
      + "        private readonly global::ConvoHop.Internal.IOperationExecutor _executor;\n\n"
      + `        internal ${className}(global::ConvoHop.Internal.IOperationExecutor executor)\n        {\n`
      + "            _executor = executor ?? throw new global::System.ArgumentNullException(nameof(executor));\n        }\n"
      + methods.map(method => `\n${method}`).join("")
      + "    }\n";
  });
}

export default defineEmitter({
  name: "csharp",
  description: "C# models, operation descriptors and schema metadata for the ConvoHop .NET SDK",
  owns: [DEFAULT_DIRECTORY],
  emit(ir, { directory = DEFAULT_DIRECTORY, layers = DEFAULT_LAYERS } = {}) {
    if (!Array.isArray(layers) || layers.length === 0 || !layers.every(layer => LAYERS.has(layer))) {
      throw new EmitterError(`csharp: layers must be a non-empty list of ${[...LAYERS].join(", ")}`);
    }
    const { types, operations, reached } = selectOperations(ir, layers);
    const enums = reached.filter(type => type.kind === "enum");
    const enumHeader = "#pragma warning disable CS0618 // Deprecated schema values stay mapped.\n";
    const operationsHeader = "#pragma warning disable CS0618 // Deprecated operations stay listed.\n";
    const apisHeader = "#pragma warning disable CS0618 // Deprecated operations stay callable.\n";
    const apis = renderApis(ir, describeApis(ir, operations, types), types);
    return [
      file(directory, "Enums.cs", "ConvoHop.Models", renderEnums(enums)),
      file(directory, "EnumConverters.cs", "ConvoHop.Generated", renderEnumConverters(enums), enumHeader),
      file(directory, "Inputs.cs", "ConvoHop.Models", renderInputs(reached.filter(type => type.kind === "input"), types)),
      file(directory, "Outputs.cs", "ConvoHop.Models", renderOutputs(reached.filter(type => type.kind === "object"), types)),
      file(directory, "Operations.cs", "ConvoHop", renderOperations(ir, operations, types), operationsHeader),
      file(directory, "ErrorCodes.cs", "ConvoHop", renderErrorCodes(ir)),
      file(directory, "Schema.cs", "ConvoHop.Generated", renderSchema(reached)),
      file(directory, "JsonContext.cs", "ConvoHop.Generated", renderJsonContext(operations, reached, types)),
      file(directory, "Apis.cs", "ConvoHop.Api", apis, apisHeader),
    ];
  },
});
