import { defineEmitter, EmitterError } from "../lib/emitter.mjs";
import { byName, namedTypeRef, printTypeRef, requireType } from "../lib/ir-model.mjs";
import { capitalize, codeUnitCompare, words } from "../lib/naming.mjs";

/**
 * Go types, clients and runtime catalog for the github.com/ConvoHop/sdks/go
 * module (package convohop).
 *
 * Writes three files into options.directory (default "go"):
 *   types_gen.go       scalar aliases, error codes and schema types;
 *   operations_gen.go  one client per plane with a method per server operation;
 *   catalog_gen.go     the tables that the hand-written runtime reads.
 * Only server-runtime operations become methods; client-layer operations and
 * subscriptions belong to the browser and mobile SDKs. options.clients maps a
 * plane name to its client type name (default: the plane name + "Client").
 *
 * The output is gofmt-clean without running gofmt: the emitter reproduces
 * gofmt's column alignment and writes doc comments in canonical form. The Go
 * test (tools/sdkgen/test/go.test.mjs) checks both with the real toolchain.
 */
export const DEFAULT_DIRECTORY = "go";

const HEADER = "// Code generated by sdkgen. DO NOT EDIT.\n// Run npm run generate:graphql to regenerate.\n\npackage convohop\n";
// graphql-js prints `@deprecated` without a reason as this default.
const DEFAULT_DEPRECATION_REASON = "No longer supported";
const REPRESENTATIONS = { string: "string", integer: "int64", number: "float64", boolean: "bool", object: "map[string]any" };
const REPRESENTATION_NAMES = new Set(Object.keys(REPRESENTATIONS));

// Go's common initialisms (golint), written upper-case inside identifiers.
const INITIALISMS = new Set([
  "acl", "api", "ascii", "cpu", "css", "dns", "eof", "guid", "html", "http", "https", "id", "ip", "json", "lhs", "qps",
  "ram", "rhs", "rpc", "sla", "smtp", "sql", "ssh", "tcp", "tls", "ttl", "udp", "ui", "uid", "uuid", "uri", "url",
  "utf8", "vm", "xml", "xmpp", "xsrf", "xss",
]);
const PLURAL_INITIALISMS = new Map(["acls", "apis", "cpus", "ids", "ips", "uids", "uris", "urls", "uuids", "vms"]
  .map(word => [word, `${word.slice(0, -1).toUpperCase()}s`]));
const SPELLINGS = new Map([["graphql", "GraphQL"]]);

/**
 * Package-level identifiers that the hand-written runtime declares. Generated
 * names must not collide with them; the Go build catches any that this list
 * misses.
 */
export const RUNTIME_IDENTIFIERS = Object.freeze([
  "CallOption", "ErrRefreshRequired", "ErrorCode", "ManagementConfig", "MemoryRecoveryStore", "NewManagementClient",
  "NewMemoryRecoveryStore", "NewProjectClient", "NewRequestID", "Option", "Outcome", "OutcomeAccepted", "OutcomeCommitted",
  "OutcomeRejected", "OutcomeUnknown", "Problem", "ProjectConfig", "RecoveryRecord", "RecoveryStore", "WithClock",
  "WithHTTPClient", "WithRecoveryStore", "WithRequestID", "WithTimeout",
]);
/** Methods that the hand-written runtime adds to clients. */
export const RUNTIME_METHODS = Object.freeze(["Initialize", "RecoveryRecords", "Retry"]);

const fail = (where, message) => { throw new EmitterError(`go: ${where}: ${message}`); };

function goWords(text) {
  return words(text).map(word => SPELLINGS.get(word) ?? PLURAL_INITIALISMS.get(word) ??
    (INITIALISMS.has(word) ? word.toUpperCase() : capitalize(word))).join("");
}

/** The exported Go identifier for an IR name: `fetchHTTPStatus` → `FetchHTTPStatus`, `principalIds` → `PrincipalIDs`. */
export function goName(text, where = text) {
  const name = goWords(text);
  if (!/^[A-Z][A-Za-z0-9]*$/.test(name)) fail(where, `${JSON.stringify(text)} does not map to an exported Go identifier`);
  return name;
}

/** One Go scope; claiming a name twice fails with both owners. */
class Namespace {
  constructor(label, reserved = [], owner = "the hand-written runtime") {
    this.label = label;
    this.names = new Map(reserved.map(name => [name, owner]));
  }

  claim(name, owner) {
    const previous = this.names.get(name);
    if (previous !== undefined) fail(owner, `maps to ${name}, which ${previous} already uses in ${this.label}`);
    this.names.set(name, owner);
    return name;
  }
}

function checkText(text, where) {
  if (typeof text !== "string") fail(where, "text must be a string");
  if (!text.isWellFormed()) fail(where, "text contains a lone surrogate");
  if (/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f\ufeff]/.test(text)) fail(where, "text contains a control character");
  return text;
}

/** An interpreted Go string literal. */
export function goString(text, where = "string literal") {
  let out = "\"";
  for (const char of checkTextForLiteral(text, where)) {
    const code = char.codePointAt(0);
    if (char === "\\") out += "\\\\";
    else if (char === "\"") out += "\\\"";
    else if (char === "\n") out += "\\n";
    else if (char === "\r") out += "\\r";
    else if (char === "\t") out += "\\t";
    else if (code < 0x20 || code === 0x7f) out += `\\x${code.toString(16).padStart(2, "0")}`;
    else if (code === 0xfeff) out += "\\uFEFF";
    else out += char;
  }
  return `${out}"`;
}

function checkTextForLiteral(text, where) {
  if (typeof text !== "string") fail(where, "expected a string");
  if (!text.isWellFormed()) fail(where, "text contains a lone surrogate");
  return text;
}

/** A raw string literal when the text allows one, else an interpreted literal. */
function goStringBlock(text, where) {
  return /^[\x20-\x5f\x61-\x7e\n]*$/.test(text) ? `\`${text}\`` : goString(text, where);
}

/** IR prose as trimmed, non-empty lines. */
function textLines(text, where) {
  if (text === undefined) return [];
  return checkText(text, where).split(/\r\n|\r|\n/).map(line => line.trim()).filter(Boolean);
}

const sentence = text => (/[.!?]$/.test(text) ? text : `${text}.`);
const list = items => (items.length < 2 ? items.join("") : `${items.slice(0, -1).join(", ")} and ${items.at(-1)}`);

/**
 * go/doc/comment's old-style heading rule (isOldHeading). gofmt would rewrite
 * such a line as a `# heading`, so generated doc comments must never contain one.
 */
function isOldHeading(lines, offset) {
  if (offset <= 0 || lines[offset - 1] !== "" || offset + 2 >= lines.length || lines[offset + 1] !== "" ||
      /^\s/.test(lines[offset + 2])) return false;
  const line = lines[offset].trim();
  if (!/^\p{Lu}/u.test(line) || !/[\p{L}\p{Nd}]$/u.test(line)) return false;
  if (/[;:!?+*/=[\]{}_^°&§~%#@<">\\]/.test(line)) return false;
  for (let rest = line, at = rest.indexOf("'"); at >= 0; at = rest.indexOf("'")) {
    rest = rest.slice(at + 1);
    if (rest !== "s" && !rest.startsWith("s ")) return false;
  }
  for (let rest = line, at = rest.indexOf("."); at >= 0; at = rest.indexOf(".")) {
    rest = rest.slice(at + 1);
    if (rest === "" || rest.startsWith(" ")) return false;
  }
  return true;
}

/**
 * `//` comment lines from paragraphs of text lines. Top-level doc comments
 * (indent "") must already be in the canonical form that gofmt prints, so
 * they may not contain headings, link definitions or the `` and '' quote
 * pairs that go/doc/comment rewrites as curly quotes. Every line is already
 * trimmed, so none can start a code block or list.
 */
function comment(paragraphs, where, indent = "") {
  const lines = [];
  for (const paragraph of paragraphs.filter(lines => lines.length)) {
    if (lines.length) lines.push("");
    lines.push(...paragraph);
  }
  if (!indent) {
    lines.forEach((line, offset) => {
      if (/^#(\s|$)/.test(line) || /^\[[^\]]+\]:/.test(line) || /``|''/.test(line) || isOldHeading(lines, offset)) {
        fail(where, `doc comment line ${JSON.stringify(line)} would be reformatted by gofmt`);
      }
    });
  }
  return lines.map(line => `${indent}//${line ? ` ${line}` : ""}\n`).join("");
}

const deprecation = (deprecated, where) => (deprecated
  ? [`Deprecated: ${sentence(textLines(deprecated.reason ?? DEFAULT_DEPRECATION_REASON, where).join(" "))}`]
  : []);

/** Rows of cells aligned the way gofmt's tabwriter aligns one section: every cell but the last padded to the widest plus one. */
function alignRows(rows) {
  const widths = [];
  for (const row of rows) row.slice(0, -1).forEach((cell, index) => { widths[index] = Math.max(widths[index] ?? 0, cell.length); });
  return rows.map(row => row.map((cell, index) => (index < row.length - 1 ? cell.padEnd(widths[index] + 1) : cell)).join(""));
}

/**
 * Lines of declarations (struct fields or const specs) where an entry with a
 * comment starts a new alignment section, as the comment line ends gofmt's
 * column block. Entries are `{ comment, cells }`.
 */
function sectionedRows(entries, indent) {
  const out = [];
  let section = [];
  const flush = () => { out.push(...alignRows(section).map(line => `${indent}${line}\n`)); section = []; };
  for (const entry of entries) {
    if (entry.comment) {
      flush();
      out.push(entry.comment);
    }
    section.push(entry.cells);
  }
  flush();
  return out.join("");
}

/**
 * The body lines of a multi-line keyed composite literal, one `key: value` per
 * line. gofmt aligns the values of consecutive single-line entries in a
 * column and starts a new section at multi-line entries or where its key-size
 * heuristic (go/printer exprList) says the keys differ too much.
 */
function keyedLines(entries, indent) {
  const sections = [];
  let section = [];
  let previousSize = 0;
  let count = 0;
  let lnsum = 0;
  entries.forEach(({ key, value }, index) => {
    const size = value.includes("\n") ? 0 : key.length;
    let newSection = true;
    if (previousSize > 0 && size > 0) {
      if (count === 0 || (previousSize <= 40 && size <= 40)) newSection = false;
      else {
        const ratio = size / Math.exp(lnsum / count);
        newSection = 2.5 * ratio <= 1 || ratio >= 2.5;
      }
    }
    if (index > 0 && newSection) {
      sections.push(section);
      section = [];
      lnsum = 0;
      count = 0;
    }
    section.push({ key, value, size });
    if (size > 0) {
      lnsum += Math.log(size);
      count++;
    }
    previousSize = size;
  });
  sections.push(section);
  return sections.map(entries => {
    const width = Math.max(...entries.filter(entry => entry.size > 0).map(entry => entry.key.length + 2), 0);
    return entries.map(({ key, value, size }) => `${indent}${size > 0 ? `${key}:`.padEnd(width) : `${key}: `}${value},\n`).join("");
  }).join("");
}

const LAYERS = new Set(["client", "server", "both"]);
// The runtime's pageOrder for each pagination style order that takes a cursor.
const PAGE_ORDER = new Map([["server", "serverOrder"], ["ascending", "ascendingOrder"], ["descending", "descendingOrder"]]);
const ID_SCALARS = new Set(["ID", "UUID"]);
const isIdRef = ref => ref.kind === "scalar" && ID_SCALARS.has(ref.name);

/**
 * Everything the renderers need, derived once from the IR: the exposed
 * operations grouped by client, the reachable schema types and their Go
 * names. Fails on anything the Go SDK cannot represent faithfully.
 */
function createModel(ir, options) {
  const types = byName(ir.types);
  const credentials = byName(ir.credentials);
  const idempotency = byName(ir.idempotency);
  const pagination = byName(ir.pagination);
  const lookup = (catalog, name, what, where) => catalog.get(name) ?? fail(where, `references unknown ${what} ${JSON.stringify(name)}`);
  const planes = new Map(ir.planes.map(plane => [plane.name, plane]));
  const resolveOperations = new Set(ir.planes.map(plane => plane.resolveOperation).filter(Boolean));
  const global = new Namespace("package convohop", RUNTIME_IDENTIFIERS);

  const exposed = ir.operations.filter(operation => {
    if (!LAYERS.has(operation.layer)) fail(operation.id, `has unknown layer ${JSON.stringify(operation.layer)}`);
    lookup(planes, operation.plane, "plane", operation.id);
    return operation.layer !== "client" && operation.kind !== "subscription";
  });

  function serverAuth(operation) {
    const where = operation.id;
    const entries = operation.auth
      .map(entry => ({ entry, credential: lookup(credentials, entry.credential, "credential", where) }))
      .filter(({ credential }) => credential.runtime === "server");
    if (!entries.length) fail(where, "accepts no server-runtime credential");
    const carriers = new Set(entries.map(({ credential }) => credential.carrier));
    if (carriers.size > 1) fail(where, "mixes bearer and context credentials");
    const names = [...new Set(entries.map(({ credential }) => credential.name))];
    if (names.length > 1) fail(where, `accepts more than one server credential (${names.join(", ")})`);
    const { credential } = entries[0];
    if (credential.carrier === "bearer") return { entries, bearer: credential };
    if (credential.carrier !== "context") fail(where, `credential ${credential.name} has unknown carrier ${JSON.stringify(credential.carrier)}`);
    const use = operation.context.fields.find(field => field.name === credential.contextField)?.use;
    if (use !== "required") fail(where, `must require context field ${credential.contextField} for ${credential.name}`);
    const field = requireType(types, operation.context.type, where).fields.find(field => field.name === credential.contextField) ??
      fail(where, `context type ${operation.context.type} has no field ${credential.contextField}`);
    return { entries, permit: { credential, field } };
  }

  const clients = [];
  for (const plane of ir.planes) {
    const operations = exposed.filter(operation => operation.plane === plane.name);
    if (!operations.length) continue;
    const where = `plane ${plane.name}`;
    const name = options.clients?.[plane.name] ?? `${goName(plane.name, where)}Client`;
    if (!/^[A-Z][A-Za-z0-9]*$/.test(name)) fail(where, `client name ${JSON.stringify(name)} is not an exported Go identifier`);
    const client = { plane, name: global.claim(name, `the ${plane.name} client`), methods: new Namespace(`${name}'s methods`, RUNTIME_METHODS) };
    client.operations = operations.map(operation => {
      const where = operation.id;
      for (const argument of operation.arguments) {
        if (argument.role !== "context" && argument.role !== "input") fail(where, `argument ${argument.name} has unsupported role ${JSON.stringify(argument.role)}`);
      }
      const auth = serverAuth(operation);
      if (auth.bearer) {
        if (client.bearer && client.bearer !== auth.bearer) fail(where, `uses bearer ${auth.bearer.name}, but other ${plane.name} operations use ${client.bearer.name}`);
        client.bearer = auth.bearer;
      }
      return {
        operation,
        client,
        auth,
        method: client.methods.claim(goName(operation.field, where), where),
        idempotency: lookup(idempotency, operation.idempotency, "idempotency class", where),
        pagination: lookup(pagination, operation.pagination.style, "pagination style", where),
      };
    });
    clients.push(client);
  }
  const models = new Map(clients.flatMap(client => client.operations.map(model => [model.operation.id, model])));

  // Reachable schema types: inputs from operation inputs (and permit
  // arguments), outputs from results, enums and scalars from both.
  const inputs = new Set();
  const outputs = new Set();
  function visit(name, input, where) {
    const seen = input ? inputs : outputs;
    if (seen.has(name)) return;
    const type = requireType(types, name, where);
    seen.add(name);
    if (type.kind === "input" || type.kind === "object") {
      if ((type.kind === "input") !== input) fail(where, `uses ${type.kind} type ${name} in ${input ? "an input" : "an output"} position`);
      for (const field of type.fields) visit(namedTypeRef(field.type).name, input, `${name}.${field.name}`);
    } else if (type.kind !== "enum" && type.kind !== "scalar") fail(where, `type ${name} has unsupported kind ${JSON.stringify(type.kind)}`);
  }
  for (const { operation, auth } of models.values()) {
    if (operation.input) visit(operation.input.type, true, operation.id);
    if (auth.permit) visit(namedTypeRef(auth.permit.field.type).name, true, operation.id);
    visit(namedTypeRef(operation.result.type).name, false, operation.id);
  }
  const reachable = [...new Set([...inputs, ...outputs])].sort(codeUnitCompare).map(name => types.get(name));

  const goTypes = new Map();
  for (const type of reachable) {
    if (type.kind === "scalar") {
      const representation = REPRESENTATIONS[type.representation] ?? fail(type.name, `has unknown representation ${JSON.stringify(type.representation)}`);
      if (type.builtIn) {
        goTypes.set(type.name, representation);
        continue;
      }
    }
    goTypes.set(type.name, global.claim(goName(type.name), `type ${type.name}`));
  }
  const goType = name => goTypes.get(name) ?? fail(name, "is not a reachable type");
  const isObjectScalar = name => {
    const type = types.get(name);
    return type.kind === "scalar" && type.representation === "object";
  };
  // nil maps and slices are the absent value, so they are never pointers.
  const inputGoType = (ref, optional) => {
    if (ref.kind === "list") return `[]${inputGoType(ref.ofType, ref.ofType.nullable)}`;
    return optional && !isObjectScalar(ref.name) ? `*${goType(ref.name)}` : goType(ref.name);
  };
  const outputGoType = ref => {
    if (ref.kind === "list") return `[]${outputGoType(ref.ofType)}`;
    return ref.nullable && !isObjectScalar(ref.name) ? `*${goType(ref.name)}` : goType(ref.name);
  };
  const isOptionalInput = field => field.type.nullable || field.defaultValue !== undefined;
  const resultGoType = ref => (ref.kind === "object" ? `*${goType(ref.name)}` : outputGoType(ref));

  // Go cannot embed a struct in itself by value.
  const embedded = type => type.fields
    .filter(field => field.type.kind === (type.kind === "input" ? "input" : "object") &&
      (type.kind === "input" ? !isOptionalInput(field) : !field.type.nullable))
    .map(field => field.type.name);
  const state = new Map();
  const walk = (name, path) => {
    if (state.get(name) === "done") return;
    if (state.get(name) === "active") fail(name, `embeds itself by value through ${[...path, name].join(" → ")}`);
    state.set(name, "active");
    for (const next of embedded(types.get(name))) walk(next, [...path, name]);
    state.set(name, "done");
  };
  for (const type of reachable) if (type.kind === "input" || type.kind === "object") walk(type.name, []);

  // The page iterator for cursor-style operations whose shape the runtime's
  // paginate helper understands; anything else keeps only the plain method.
  // Ordered styles with a decimal cursor check that each next cursor moves in
  // that order; other cursors must differ from every cursor already sent.
  const stringScalar = ref => ref?.kind === "scalar" && types.get(ref.name)?.representation === "string";
  const booleanField = (type, name) => {
    const ref = type.fields.find(field => field.name === name)?.type;
    return ref?.kind === "scalar" && ref.name === "Boolean" && !ref.nullable;
  };
  function pagesOf(model) {
    const { operation } = model;
    const page = operation.pagination;
    if (!model.pagination.cursorInput || !page.cursorField || !page.pagePath || !operation.input) return undefined;
    const cursor = requireType(types, operation.input.type, operation.id).fields.find(field => field.name === page.cursorField);
    if (!cursor || !cursor.type.nullable || !stringScalar(cursor.type)) return undefined;
    const path = [];
    let ref = operation.result.type;
    for (const segment of page.pagePath) {
      if (ref.kind !== "object") return undefined;
      const field = types.get(ref.name).fields.find(field => field.name === segment);
      if (!field) return undefined;
      path.push({ name: goName(field.name), nullable: field.type.nullable });
      ref = field.type;
    }
    if (ref.kind !== "object" || ref.name !== page.pageType) return undefined;
    const pageType = types.get(ref.name);
    const next = pageType.fields.find(field => field.name === "nextCursor")?.type;
    if (!booleanField(pageType, "complete") || !booleanField(pageType, "refreshRequired") || !next?.nullable ||
        next.name !== "String") return undefined;
    const order = PAGE_ORDER.get(model.pagination.order) ??
      fail(operation.id, `pagination style ${model.pagination.name} has unsupported order ${JSON.stringify(model.pagination.order)}`);
    const decimal = types.get(cursor.type.name).constraints?.maximumDecimal !== undefined;
    return {
      cursor: goName(cursor.name),
      scalar: cursor.type.name,
      order: decimal ? order : PAGE_ORDER.get("server"),
      path,
      pageType: goType(pageType.name),
    };
  }
  for (const client of clients) {
    for (const model of client.operations) {
      model.pages = pagesOf(model);
      if (model.pages) model.pages.method = client.methods.claim(`${model.method}Pages`, `${model.operation.id} pages`);
    }
  }

  // Runtime response checks: the envelope flag, whether the envelope must
  // carry its result, and input ID fields that the result must echo (on every
  // page item, the envelope result or the result).
  const isEnvelope = ref => ref.kind === "object" && !ref.nullable &&
    ["status", "requestId"].every(name => types.get(ref.name).fields.some(field => field.name === name));
  // As in the other SDKs, a reply envelope with an operation reference must
  // carry its nullable result unless the operation is long-running. A
  // non-null result is already required by its type.
  const requiresResult = operation => {
    const fields = types.get(operation.result.type.name).fields;
    return !operation.longRunning && fields.some(field => field.name === "operation") &&
      Boolean(fields.find(field => field.name === "result")?.type.nullable);
  };
  for (const model of models.values()) {
    const { operation } = model;
    model.envelope = isEnvelope(operation.result.type);
    model.requireResult = model.envelope && requiresResult(operation);
    model.subject = operation.pagination.pagePath ? [...operation.pagination.pagePath, "items"] : model.envelope ? ["result"] : [];
    model.echo = [];
    if (!operation.input || resolveOperations.has(operation.id)) continue;
    let ref = operation.result.type;
    for (const segment of model.subject) {
      const field = types.get(namedTypeRef(ref).name).fields?.find(field => field.name === segment) ??
        fail(operation.id, `result has no field ${model.subject.join(".")}`);
      ref = field.type;
    }
    const subject = types.get(namedTypeRef(ref).name);
    if (subject.kind !== "object") continue;
    model.echo = requireType(types, operation.input.type, operation.id).fields
      .filter(field => field.name.endsWith("Id") && isIdRef(field.type) &&
        subject.fields.some(other => other.name === field.name && isIdRef(other.type)))
      .map(field => field.name);
  }

  return {
    ir, types, global, clients, models, reachable, goType, inputGoType, outputGoType, resultGoType, isOptionalInput,
    isObjectScalar, inputs, outputs, lookup,
  };
}

const ORIGINS = { server: "Raised by the server.", both: "Raised by the server or the SDK.", sdk: "Raised by the SDK." };
const exported = (name, where) => {
  if (!/^[A-Z][A-Za-z0-9]*$/.test(name)) fail(where, `maps to ${JSON.stringify(name)}, which is not an exported Go identifier`);
  return name;
};
const plural = (count, noun) => `${count} ${noun}${count === 1 ? "" : "s"}`;
const duration = ms => (ms % 1000 === 0 ? plural(ms / 1000, "second") : plural(ms, "millisecond"));

function renderTypes(model) {
  const { ir, global, reachable, goType, inputGoType, outputGoType, isOptionalInput } = model;
  const declarations = [];

  for (const type of reachable.filter(type => type.kind === "scalar" && !type.builtIn)) {
    const name = goType(type.name);
    const doc = comment([[`${name} is the GraphQL scalar ${type.name}.`, ...textLines(type.description ?? type.summary, type.name)]], type.name);
    declarations.push(`${doc}type ${name} = ${REPRESENTATIONS[type.representation]}\n`);
  }

  const codes = ir.errors.codes.map(code => {
    const where = `error code ${code.name}`;
    const name = global.claim(exported(`ErrorCode${goWords(code.name)}`, where), where);
    const facts = [
      ...(code.status === undefined ? [] : [`HTTP status ${code.status}.`]),
      code.retryable ? "Retryable." : "Not retryable.",
      ORIGINS[code.origin] ?? fail(where, `has unknown origin ${JSON.stringify(code.origin)}`),
    ];
    return { name, retryable: code.retryable, comment: comment([[...textLines(code.summary, where), facts.join(" ")]], where, "\t"), cells: [name, "ErrorCode", `= ${goString(code.name)}`] };
  });
  if (codes.length) {
    declarations.push(`// Error codes reported in [Problem]. Classify errors by code, never by message text.\nconst (\n${sectionedRows(codes, "\t")})\n`);
  }
  const retryable = codes.filter(code => code.retryable).map(code => code.name);
  declarations.push("// Retryable reports whether the API documents the error code as retryable with the same request ID.\n" +
    `func (c ErrorCode) Retryable() bool {\n${retryable.length ? `\tswitch c {\n\tcase ${retryable.join(", ")}:\n\t\treturn true\n\t}\n` : ""}\treturn false\n}\n`);

  for (const type of reachable) {
    if (type.kind === "enum") {
      const name = goType(type.name);
      declarations.push(`${comment([[`${name} is the GraphQL enum ${type.name}.`, ...textLines(type.description, type.name)]], type.name)}type ${name} string\n`);
      const values = type.values.map(value => {
        const where = `${type.name}.${value.name}`;
        const constant = global.claim(exported(`${name}${goWords(value.name)}`, where), where);
        const paragraphs = [textLines(value.description, where), deprecation(value.deprecated, where)];
        return { comment: comment(paragraphs, where, "\t"), cells: [constant, name, `= ${goString(value.name)}`] };
      });
      declarations.push(`// ${name} values.\nconst (\n${sectionedRows(values, "\t")})\n`);
    } else if (type.kind === "input" || type.kind === "object") {
      const name = goType(type.name);
      const input = type.kind === "input";
      const doc = comment([[`${name} is the GraphQL ${type.kind} ${type.name}.`, ...textLines(type.description, type.name)]], type.name);
      const names = new Namespace(`struct ${name}`);
      const fields = type.fields.map(field => {
        const where = `${type.name}.${field.name}`;
        if (!/^[_A-Za-z][_0-9A-Za-z]*$/.test(field.name)) fail(where, "is not a GraphQL name");
        const optional = input && isOptionalInput(field);
        const notes = input && field.defaultValue !== undefined ? [`Default: ${JSON.stringify(field.defaultValue)}.`] : [];
        const paragraphs = [[...textLines(field.description, where), ...notes], deprecation(field.deprecated, where)];
        return {
          comment: comment(paragraphs, where, "\t"),
          cells: [
            names.claim(goName(field.name, where), where),
            input ? inputGoType(field.type, optional) : outputGoType(field.type),
            `\`json:"${field.name}${optional ? ",omitzero" : ""}"\``,
          ],
        };
      });
      declarations.push(`${doc}type ${name} struct${fields.length ? ` {\n${sectionedRows(fields, "\t")}}` : "{}"}\n`);
    }
  }
  return `${HEADER}${declarations.map(declaration => `\n${declaration}`).join("")}`;
}

function authSentence(model) {
  if (model.auth.permit) return `Authorized by ${model.auth.permit.credential.name}, sent as the permit argument without a bearer token.`;
  const phrases = model.auth.entries.map(({ entry }) => {
    let phrase = entry.credential;
    if (entry.scopes?.length) phrase += ` with ${entry.scopes.length === 1 ? "scope" : "all of the scopes"} ${list(entry.scopes)}`;
    if (entry.condition) phrase += ` (condition: ${entry.condition})`;
    return phrase;
  });
  return phrases.length === 1 ? `Authorized by ${phrases[0]}.` : `Authorized by any one of: ${phrases.join("; ")}.`;
}

function methodDoc(models, model) {
  const { operation, client } = model;
  const where = operation.id;
  const lead = [`${model.method} calls the ${operation.id} ${operation.kind}.`, ...textLines(operation.summary, where), ...textLines(operation.description, where)];
  const facts = [`Idempotency: ${operation.idempotency}. ${sentence(model.idempotency.summary)}`];
  const budget = model.idempotency.retryBudget;
  if (budget) facts.push(`Retry budget: ${plural(budget.maxAttempts, "attempt")} within ${duration(budget.windowMs)}.`);
  if (operation.pagination.style !== "none") {
    const pages = model.pages ? ` [${client.name}.${model.pages.method}] iterates over the pages.` : "";
    facts.push(`Pagination: ${operation.pagination.style}. ${sentence(model.pagination.summary)}${pages}`);
  }
  if (operation.longRunning) {
    const { poll, refField } = operation.longRunning;
    const target = models.get(poll)?.client === client ? `[${client.name}.${models.get(poll).method}]` : poll;
    facts.push(`Long-running: poll ${target} with the reply's ${goName(refField, where)} reference until the work completes.`);
  }
  if (operation.realtime?.emits?.length) facts.push(`Realtime events: ${list(operation.realtime.emits)}.`);
  facts.push(authSentence(model));
  return comment([lead, facts, deprecation(operation.deprecated, where)], where);
}

function permitParameter(model, goType) {
  const ref = model.auth.permit.field.type;
  if (ref.kind === "list") fail(model.operation.id, "permit context field must not be a list");
  return `permit ${goType(ref.name)}`;
}

function renderMethod(shared, model) {
  const { operation, client } = model;
  const parameters = ["ctx context.Context"];
  if (model.auth.permit) parameters.push(permitParameter(model, shared.goType));
  if (operation.input) {
    const input = shared.goType(operation.input.type);
    parameters.push(`input ${operation.input.required ? input : `*${input}`}`);
  }
  parameters.push("opts ...CallOption");
  const result = shared.resultGoType(operation.result.type);
  const call = `c.t.call(ctx, ${goString(operation.id)}, ${operation.input ? "input" : "nil"}, ${model.auth.permit ? "permit" : "nil"}, &out, opts)`;
  return `${methodDoc(shared.models, model)}func (c *${client.name}) ${model.method}(${parameters.join(", ")}) (${result}, error) {\n` +
    `\tvar out ${result}\n\terr := ${call}\n\treturn out, err\n}\n`;
}

function renderPages(shared, model) {
  const { operation, client, pages } = model;
  const where = `${operation.id} pages`;
  const doc = comment([[
    `${pages.method} iterates over the pages of [${client.name}.${model.method}], starting at input.${pages.cursor}.`,
    "Each page is a new request with a new request ID.",
    "Iteration stops after the complete page or at the first error.",
    "A page that requires a refresh yields [ErrRefreshRequired] and stops.",
    "An incomplete page whose next cursor is missing, malformed or doesn't advance yields an INVALID_RESPONSE [Problem] in place of the page and stops.",
  ]], where);
  const parameters = ["ctx context.Context"];
  const arguments_ = ["ctx"];
  if (model.auth.permit) {
    parameters.push(permitParameter(model, shared.goType));
    arguments_.push("permit");
  }
  parameters.push(`input ${shared.goType(operation.input.type)}`);
  arguments_.push(operation.input.required ? "request" : "&request");
  const missing = expression => [`\t\tif ${expression} == nil {`, "\t\t\treturn nil, pageState{}, missingPage()", "\t\t}"];
  const lines = [
    `func (c *${client.name}) ${pages.method}(${parameters.join(", ")}) iter.Seq2[*${pages.pageType}, error] {`,
    `\treturn paginate(input.${pages.cursor}, pageCursor{${goString(pages.scalar, where)}, ${pages.order}}, func(cursor *string) (*${pages.pageType}, pageState, error) {`,
    "\t\trequest := input",
    `\t\trequest.${pages.cursor} = cursor`,
    `\t\tout, err := c.${model.method}(${arguments_.join(", ")})`,
    "\t\tif err != nil {",
    "\t\t\treturn nil, pageState{}, err",
    "\t\t}",
  ];
  let expression = "out";
  if (operation.result.type.nullable) lines.push(...missing(expression));
  for (const segment of pages.path) {
    expression = `${expression}.${segment.name}`;
    if (segment.nullable) lines.push(...missing(expression));
  }
  const last = pages.path.at(-1);
  lines.push(
    `\t\tpage := ${last && !last.nullable ? `&${expression}` : expression}`,
    "\t\treturn page, pageState{page.Complete, page.RefreshRequired, page.NextCursor}, nil",
    "\t})",
    "}",
  );
  return `${doc}${lines.join("\n")}\n`;
}

function clientDoc(client) {
  const where = client.name;
  const credentials = new Map(client.operations.flatMap(model => model.auth.entries.map(({ credential }) => [credential.name, credential])));
  const lines = [...credentials.values()].map(credential =>
    `${credential.carrier === "bearer" ? "Bearer" : "Context"} credential: ${credential.name}. ${sentence(textLines(credential.summary, where).join(" "))}`);
  return comment([[`${client.name} calls the ${client.plane.name} plane.`, ...textLines(client.plane.summary, where)], lines], where);
}

function renderOperations(shared) {
  const methods = shared.clients.flatMap(client => client.operations);
  const imports = [...(methods.length ? ["context"] : []), ...(methods.some(model => model.pages) ? ["iter"] : [])];
  const declarations = [];
  if (imports.length === 1) declarations.push(`import ${goString(imports[0])}\n`);
  else if (imports.length) declarations.push(`import (\n${imports.map(name => `\t${goString(name)}\n`).join("")})\n`);
  for (const client of shared.clients) {
    declarations.push(`${clientDoc(client)}type ${client.name} struct {\n\tt *transport\n}\n`);
    for (const model of client.operations) {
      declarations.push(renderMethod(shared, model));
      if (model.pages) declarations.push(renderPages(shared, model));
    }
  }
  return `${HEADER}${declarations.map(declaration => `\n${declaration}`).join("")}`;
}

const CONTEXT_USES = new Set(["required", "optional", "forbidden"]);
const RETRY_MODES = new Set(["none", "repeat", "sameRequest"]);
/** The scalar constraints the Go runtime enforces, by representation. Generation fails on any other. */
const SCALAR_CONSTRAINTS = {
  string: ["pattern", "disallowed", "maximumDecimal"],
  integer: ["minimum", "maximum"],
  number: ["minimum", "maximum"],
  boolean: [],
  object: ["maxCanonicalJsonBytes", "requiredStringProperties"],
};

const slice = (type, elements, indent = "") => (elements.length
  ? `[]${type}{\n${elements.map(element => `${indent}\t${element},\n`).join("")}${indent}}`
  : `[]${type}{}`);
const inline = (type, elements) => `[]${type}{${elements.join(", ")}}`;

/** The largest repeat count Go's regexp compiles. */
const GO_MAX_REPEAT = 1000;

/**
 * A scalar pattern as a Go string literal. Go's regexp (RE2) runs the pattern
 * unchanged, so only the ASCII subset where RE2 and ECMAScript agree is
 * accepted: `$` matches only at the end in both, while `.`, `\s`, groups that
 * start with `(?`, nested classes and non-ASCII text differ or do not compile.
 */
export function goPattern(pattern, where = "pattern") {
  const unsupported = detail => fail(where, `pattern ${JSON.stringify(pattern)} uses ${detail}, which the Go emitter does not translate`);
  let inClass = false;
  for (let index = 0; index < pattern.length; index++) {
    const char = pattern[index];
    if (char === "\\") {
      const next = pattern[index + 1];
      if (next === undefined || !/^[\\^$.|?*+()[\]{}/dD-]$/.test(next)) unsupported(`the escape \\${next ?? ""}`);
      index++;
    } else if (inClass) {
      if (char === "[") unsupported("[ inside a character class");
      if (!/^[ -~]$/.test(char)) unsupported("non-ASCII text");
      if (char === "]") inClass = false;
    } else if (char === "[") {
      inClass = true;
      if (pattern.startsWith("]", index + 1) || pattern.startsWith("^]", index + 1)) unsupported("an empty character class");
    } else if (char === "{") {
      const repeat = /^\{([0-9]+)(,([0-9]*))?\}/.exec(pattern.slice(index));
      if (!repeat) unsupported("a { that does not start a repeat count");
      const counts = [repeat[1], repeat[3]].filter(Boolean).map(Number);
      if (counts.some(count => count > GO_MAX_REPEAT)) unsupported(`a repeat count above ${GO_MAX_REPEAT}`);
      if (counts.length === 2 && counts[0] > counts[1]) unsupported("a repeat range whose minimum exceeds its maximum");
      index += repeat[0].length - 1;
    } else if (char === "." || (char === "(" && pattern[index + 1] === "?")) {
      unsupported(char === "." ? "." : "a (? group");
    } else if (!/^[A-Za-z0-9^$|()?*+,:_ -]$/.test(char)) {
      unsupported(JSON.stringify(char));
    }
  }
  if (inClass) unsupported("an unterminated character class");
  return goString(pattern, where);
}

function operationEntry(model) {
  const { operation } = model;
  const where = operation.id;
  const entries = [];
  const add = (key, value) => entries.push({ key, value });
  add("id", goString(operation.id));
  add("plane", goString(operation.plane));
  add("kind", goString(operation.kind));
  add("field", goString(operation.field));
  add("operationName", goString(operation.operationName));
  add("result", goString(printTypeRef(operation.result.type)));
  if (operation.input) {
    add("input", goString(operation.input.type));
    if (operation.input.required) add("inputRequired", "true");
  }
  for (const field of operation.context.fields) {
    if (!CONTEXT_USES.has(field.use)) fail(where, `context field ${field.name} has unknown use ${JSON.stringify(field.use)}`);
  }
  const context = operation.context.fields.filter(field => field.use !== "forbidden")
    .toSorted((a, b) => codeUnitCompare(a.name, b.name))
    .map(field => `${goString(field.name)}: ${goString(field.use)}`);
  if (context.length) add("context", `map[string]string{${context.join(", ")}}`);
  if (model.auth.bearer) add("bearer", goString(model.auth.bearer.name));
  if (model.auth.permit) {
    add("permitField", goString(model.auth.permit.credential.contextField));
    add("permitType", goString(printTypeRef(model.auth.permit.field.type)));
  }
  if (!RETRY_MODES.has(model.idempotency.retry)) fail(where, `idempotency class ${operation.idempotency} has unknown retry ${JSON.stringify(model.idempotency.retry)}`);
  add("retry", goString(model.idempotency.retry));
  const budget = model.idempotency.retryBudget;
  if (budget) {
    for (const key of ["maxAttempts", "windowMs"]) {
      if (!Number.isSafeInteger(budget[key]) || budget[key] < 1) fail(where, `retry budget ${key} must be a positive integer`);
    }
    add("maxAttempts", String(budget.maxAttempts));
    add("windowMs", String(budget.windowMs));
  }
  if (model.idempotency.resolvable) add("resolvable", "true");
  if (model.envelope) add("envelope", "true");
  if (model.requireResult) add("requireResult", "true");
  if (model.subject.length) add("subject", inline("string", model.subject.map(name => goString(name))));
  if (model.echo.length) add("echo", inline("string", model.echo.map(name => goString(name))));
  add("document", goStringBlock(operation.document.text, where));
  return `{\n${keyedLines(entries, "\t\t")}\t}`;
}

export function scalarEntry(type) {
  const where = `scalar ${type.name}`;
  const allowed = SCALAR_CONSTRAINTS[type.representation];
  if (!allowed) fail(where, `unsupported representation ${JSON.stringify(type.representation)}`);
  const constraints = type.constraints ?? {};
  for (const key of Object.keys(constraints)) {
    if (!allowed.includes(key)) fail(where, `unsupported ${type.representation} constraint ${key}`);
  }
  const fields = [`name: ${goString(type.name)}`, `representation: ${goString(type.representation)}`];
  if (constraints.pattern !== undefined) fields.push(`pattern: ${goPattern(constraints.pattern, where)}`);
  if (constraints.disallowed?.length) fields.push(`disallowed: ${inline("string", constraints.disallowed.map(value => goString(value, where)))}`);
  if (constraints.maximumDecimal !== undefined) {
    if (typeof constraints.maximumDecimal !== "string" || !/^(0|[1-9][0-9]*)$/.test(constraints.maximumDecimal)) {
      fail(where, "maximumDecimal must be a canonical decimal string");
    }
    fields.push(`maximumDecimal: ${goString(constraints.maximumDecimal)}`);
  }
  const { minimum, maximum } = constraints;
  for (const [key, bound] of [["minimum", minimum], ["maximum", maximum]]) {
    if (bound === undefined) continue;
    const valid = type.representation === "integer" ? Number.isSafeInteger(bound) : Number.isFinite(bound);
    const shown = typeof bound === "number" ? String(bound) : JSON.stringify(bound);
    if (!valid) fail(where, `${key} ${shown} is not a ${type.representation === "integer" ? "safe integer" : "finite number"}`);
    fields.push(`${key}: new(float64(${String(bound)}))`);
  }
  if (minimum !== undefined && maximum !== undefined && minimum > maximum) fail(where, "minimum exceeds maximum");
  if (constraints.maxCanonicalJsonBytes !== undefined) {
    if (!Number.isSafeInteger(constraints.maxCanonicalJsonBytes) || constraints.maxCanonicalJsonBytes < 1) fail(where, "maxCanonicalJsonBytes must be a positive integer");
    fields.push(`maxCanonicalJSONBytes: ${constraints.maxCanonicalJsonBytes}`);
  }
  if (constraints.requiredStringProperties?.length) {
    fields.push(`requiredStringProperties: ${inline("string", constraints.requiredStringProperties.map(name => goString(name, where)))}`);
  }
  return `{${fields.join(", ")}}`;
}

function renderCatalog(shared) {
  const { ir, clients, models, reachable } = shared;
  const ref = field => goString(printTypeRef(field.type));
  const of = kind => reachable.filter(type => type.kind === kind);
  const tables = [
    ["planes", "plane", clients.map(({ plane }) => `{${goString(plane.name)}, ${goString(plane.resolveOperation ?? "")}}`)],
    ["operations", "operation", [...models.values()].map(operationEntry)],
    ["objectTypes", "objectType", of("object").map(type =>
      `{${goString(type.name)}, ${inline("typeField", type.fields.map(field => `{${goString(field.name)}, ${ref(field)}}`))}}`)],
    ["inputTypes", "inputType", of("input").map(type =>
      `{${goString(type.name)}, ${inline("inputField", type.fields.map(field => `{${goString(field.name)}, ${ref(field)}, ${field.defaultValue !== undefined}}`))}}`)],
    ["enumTypes", "enumType", of("enum").map(type => `{${goString(type.name)}, ${inline("string", type.values.map(value => goString(value.name)))}}`)],
    ["scalarTypes", "scalarType", of("scalar").map(scalarEntry)],
  ];
  const declarations = [
    `const graphQLPath = ${goString(ir.transport.path)}\n`,
    ...tables.map(([name, type, elements]) => `var ${name} = ${slice(type, elements)}\n`),
  ];
  return `${HEADER}${declarations.map(declaration => `\n${declaration}`).join("")}`;
}

export default defineEmitter({
  name: "go",
  description: "Go types, clients and runtime catalog for github.com/ConvoHop/sdks/go",
  emit(ir, { directory = DEFAULT_DIRECTORY, ...options } = {}) {
    const model = createModel(ir, options);
    return [
      { path: `${directory}/types_gen.go`, contents: renderTypes(model) },
      { path: `${directory}/operations_gen.go`, contents: renderOperations(model) },
      { path: `${directory}/catalog_gen.go`, contents: renderCatalog(model) },
    ];
  },
});
