// Code generated by fxgen. DO NOT EDIT.

package fx

// Shape is a generated shape.
type Shape struct {
	// Sides counts the sides.
	Sides int `json:"sides"`
}

// Area is a method of a generated type.
func (s Shape) Area() float64 { return 0 }

// Kind is a generated enum.
type Kind string

// The kinds.
const (
	KindSquare Kind = "square"
	KindRound  Kind = "round"
)
