// Code generated by sdkgen. DO NOT EDIT.
// Run npm run generate:graphql to regenerate.

package convohop

const graphQLPath = "/graphql"

var planes = []plane{
	{"alpha", "alpha.resolveRequest"},
	{"beta", "beta.resolveRequest"},
}

var operations = []operation{
	{
		id:            "alpha.capabilities",
		plane:         "alpha",
		kind:          "query",
		field:         "capabilities",
		operationName: "AlphaCapabilities",
		result:        "Capabilities!",
		context:       map[string]string{"attempt": "optional", "requestId": "required", "tags": "optional", "tenant": "optional"},
		bearer:        "serverKey",
		retry:         "repeat",
		document: `query AlphaCapabilities($context: ContextInput!) {
  capabilities(context: $context) {
    version
    wssUrl
    features
  }
}`,
	},
	{
		id:            "alpha.resolveRequest",
		plane:         "alpha",
		kind:          "query",
		field:         "resolveRequest",
		operationName: "AlphaResolveRequest",
		result:        "Receipt!",
		input:         "ResolveInput",
		inputRequired: true,
		context:       map[string]string{"attempt": "optional", "requestId": "required", "tags": "optional", "tenant": "required"},
		bearer:        "serverKey",
		retry:         "repeat",
		document: `query AlphaResolveRequest($context: ContextInput!, $input: ResolveInput!) {
  resolveRequest(context: $context, input: $input) {
    requestId
    committed
    sequence
  }
}`,
	},
	{
		id:            "alpha.job",
		plane:         "alpha",
		kind:          "query",
		field:         "job",
		operationName: "AlphaJob",
		result:        "Job",
		input:         "JobInput",
		inputRequired: true,
		context:       map[string]string{"attempt": "optional", "requestId": "required", "tags": "optional", "tenant": "required"},
		bearer:        "serverKey",
		retry:         "repeat",
		echo:          []string{"operationId"},
		document: `query AlphaJob($context: ContextInput!, $input: JobInput!) {
  job(context: $context, input: $input) {
    operationId
    state
    progress
    output
  }
}`,
	},
	{
		id:            "alpha.fetchHTTPStatus",
		plane:         "alpha",
		kind:          "query",
		field:         "fetchHTTPStatus",
		operationName: "AlphaFetchHTTPStatus",
		result:        "Int",
		input:         "FetchInput",
		context:       map[string]string{"attempt": "optional", "requestId": "required", "tags": "optional", "tenant": "required"},
		bearer:        "serverKey",
		retry:         "repeat",
		document: `query AlphaFetchHTTPStatus($context: ContextInput!, $input: FetchInput) {
  fetchHTTPStatus(context: $context, input: $input)
}`,
	},
	{
		id:            "alpha.startJob",
		plane:         "alpha",
		kind:          "mutation",
		field:         "startJob",
		operationName: "AlphaStartJob",
		result:        "StartJobPayload!",
		input:         "StartJobInput",
		inputRequired: true,
		context:       map[string]string{"attempt": "optional", "requestId": "required", "tags": "optional", "tenant": "required"},
		bearer:        "serverKey",
		retry:         "sameRequest",
		maxAttempts:   3,
		windowMs:      60000,
		resolvable:    true,
		document: `mutation AlphaStartJob($context: ContextInput!, $input: StartJobInput!) {
  startJob(context: $context, input: $input) {
    requestId
    receipt {
      requestId
      committed
      sequence
    }
    job {
      operationId
      state
    }
  }
}`,
	},
	{
		id:            "alpha.redeem",
		plane:         "alpha",
		kind:          "mutation",
		field:         "redeem",
		operationName: "AlphaRedeem",
		result:        "Receipt!",
		input:         "RedeemInput",
		inputRequired: true,
		context:       map[string]string{"attempt": "optional", "permit": "required", "requestId": "required", "tags": "optional", "tenant": "required"},
		permitField:   "permit",
		permitType:    "String",
		retry:         "sameRequest",
		maxAttempts:   3,
		windowMs:      60000,
		document: `mutation AlphaRedeem($context: ContextInput!, $input: RedeemInput!) {
  redeem(context: $context, input: $input) {
    requestId
    committed
    sequence
  }
}`,
	},
	{
		id:            "beta.capabilities",
		plane:         "beta",
		kind:          "query",
		field:         "capabilities",
		operationName: "BetaCapabilities",
		result:        "Capabilities!",
		context:       map[string]string{"attempt": "optional", "requestId": "required", "tags": "optional", "tenant": "optional"},
		bearer:        "serverKey",
		retry:         "repeat",
		document: `query BetaCapabilities($context: ContextInput!) {
  capabilities(context: $context) {
    version
    wssUrl
    features
  }
}`,
	},
	{
		id:            "beta.resolveRequest",
		plane:         "beta",
		kind:          "query",
		field:         "resolveRequest",
		operationName: "BetaResolveRequest",
		result:        "Receipt!",
		input:         "ResolveInput",
		inputRequired: true,
		context:       map[string]string{"attempt": "optional", "requestId": "required", "tags": "optional", "tenant": "optional"},
		bearer:        "serverKey",
		retry:         "repeat",
		document: `query BetaResolveRequest($context: ContextInput!, $input: ResolveInput!) {
  resolveRequest(context: $context, input: $input) {
    requestId
    committed
    sequence
  }
}`,
	},
	{
		id:            "beta.widgets",
		plane:         "beta",
		kind:          "query",
		field:         "widgets",
		operationName: "BetaWidgets",
		result:        "WidgetsPayload!",
		input:         "WidgetsInput",
		context:       map[string]string{"attempt": "optional", "requestId": "required", "tags": "optional", "tenant": "optional"},
		bearer:        "serverKey",
		retry:         "repeat",
		subject:       []string{"result", "items"},
		document: `query BetaWidgets($context: ContextInput!, $input: WidgetsInput) {
  widgets(context: $context, input: $input) {
    requestId
    result {
      items {
        id
        label
        state
        revision
      }
      complete
      refreshRequired
    }
  }
}`,
	},
	{
		id:            "beta.createWidget",
		plane:         "beta",
		kind:          "mutation",
		field:         "createWidget",
		operationName: "BetaCreateWidget",
		result:        "Widget!",
		input:         "CreateWidgetInput",
		inputRequired: true,
		context:       map[string]string{"attempt": "optional", "requestId": "required", "tags": "optional", "tenant": "optional"},
		bearer:        "serverKey",
		retry:         "sameRequest",
		maxAttempts:   2,
		windowMs:      1000,
		resolvable:    true,
		document: `mutation BetaCreateWidget($context: ContextInput!, $input: CreateWidgetInput!) {
  createWidget(context: $context, input: $input) {
    id
    label
    state
    revision
  }
}`,
	},
}

var objectTypes = []objectType{
	{"Capabilities", []typeField{{"version", "String!"}, {"wssUrl", "String"}, {"features", "[String!]!"}}},
	{"Job", []typeField{{"operationId", "ID!"}, {"state", "String!"}, {"progress", "Float"}, {"output", "Blob"}}},
	{"JobRef", []typeField{{"operationId", "ID!"}, {"state", "String!"}}},
	{"Receipt", []typeField{{"requestId", "ID!"}, {"committed", "Boolean!"}, {"sequence", "Counter"}}},
	{"StartJobPayload", []typeField{{"requestId", "ID!"}, {"receipt", "Receipt!"}, {"job", "JobRef"}}},
	{"Widget", []typeField{{"id", "ID!"}, {"label", "String"}, {"state", "WidgetState!"}, {"revision", "Counter!"}}},
	{"WidgetPage", []typeField{{"items", "[Widget!]!"}, {"complete", "Boolean!"}, {"refreshRequired", "Boolean!"}}},
	{"WidgetsPayload", []typeField{{"requestId", "ID!"}, {"result", "WidgetPage"}}},
}

var inputTypes = []inputType{
	{"CreateWidgetInput", []inputField{{"label", "String!", false}, {"state", "WidgetState", true}, {"ratio", "Ratio", true}, {"nested", "[[Int!]!]", false}, {"shape", "ShapeInput", true}}},
	{"FetchInput", []inputField{{"method", "HTTPMethod", true}}},
	{"JobInput", []inputField{{"operationId", "ID!", false}}},
	{"RedeemInput", []inputField{{"deliveryId", "ID!", false}}},
	{"ResolveInput", []inputField{{"requestId", "ID!", false}}},
	{"ShapeInput", []inputField{{"kind", "String!", false}, {"sides", "[Int!]!", false}}},
	{"StartJobInput", []inputField{{"itemId", "ID!", false}, {"repeat", "Int", true}, {"props", "Blob", false}}},
	{"WidgetsInput", []inputField{{"states", "[WidgetState!]", false}}},
}

var enumTypes = []enumType{
	{"HTTPMethod", []string{"POST", "GET"}},
	{"WidgetState", []string{"ACTIVE", "ARCHIVED"}},
}

var scalarTypes = []scalarType{
	{name: "Blob", representation: "object", maxCanonicalJSONBytes: 1024, requiredStringProperties: []string{"signature"}},
	{name: "Boolean", representation: "boolean"},
	{name: "Counter", representation: "string", pattern: "^(0|[1-9][0-9]*)$", maximumDecimal: "9223372036854775807"},
	{name: "Float", representation: "number"},
	{name: "ID", representation: "string"},
	{name: "Int", representation: "integer"},
	{name: "Ratio", representation: "number", minimum: new(float64(0)), maximum: new(float64(1))},
	{name: "String", representation: "string"},
}
