// Code generated by sdkgen. DO NOT EDIT.
// Run npm run generate:graphql to regenerate.

package convohop

import "context"

// AlphaClient calls the alpha plane.
// Items, jobs and realtime events.
//
// Bearer credential: serverKey. Scoped key for server runtimes.
// Context credential: permit. Single-use permit sent in the request context.
type AlphaClient struct {
	t *transport
}

// Capabilities calls the alpha.capabilities query.
// Read the server capabilities.
// Server capabilities.
//
// Idempotency: safe. Read-only. Repeat freely.
// Authorized by serverKey.
func (c *AlphaClient) Capabilities(ctx context.Context, opts ...CallOption) (*Capabilities, error) {
	var out *Capabilities
	err := c.t.call(ctx, "alpha.capabilities", nil, nil, &out, opts)
	return out, err
}

// ResolveRequest calls the alpha.resolveRequest query.
// Look up the outcome of an earlier alpha mutation by requestId.
//
// Idempotency: safe. Read-only. Repeat freely.
// Authorized by serverKey with scope itemRead.
func (c *AlphaClient) ResolveRequest(ctx context.Context, input ResolveInput, opts ...CallOption) (*Receipt, error) {
	var out *Receipt
	err := c.t.call(ctx, "alpha.resolveRequest", input, nil, &out, opts)
	return out, err
}

// Job calls the alpha.job query.
// Poll a job that alpha.startJob started.
//
// Idempotency: safe. Read-only. Repeat freely.
// Authorized by serverKey with scope itemRead.
func (c *AlphaClient) Job(ctx context.Context, input JobInput, opts ...CallOption) (*Job, error) {
	var out *Job
	err := c.t.call(ctx, "alpha.job", input, nil, &out, opts)
	return out, err
}

// FetchHTTPStatus calls the alpha.fetchHTTPStatus query.
// Fetch a <status> for `GET` | *POST* calls, with #tags, {braces}, [links], ~tildes~, & a back\slash for _escaping_ in snake_case.
//
// Idempotency: safe. Read-only. Repeat freely.
// Authorized by serverKey with all of the scopes itemRead and widgetWrite.
//
// Deprecated: Use capabilities.
func (c *AlphaClient) FetchHTTPStatus(ctx context.Context, input *FetchInput, opts ...CallOption) (*int64, error) {
	var out *int64
	err := c.t.call(ctx, "alpha.fetchHTTPStatus", input, nil, &out, opts)
	return out, err
}

// StartJob calls the alpha.startJob mutation.
// Start a job. It finishes asynchronously.
//
// Idempotency: idempotent. Retry with the same requestId and input; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Long-running: poll [AlphaClient.Job] with the reply's Job reference until the work completes.
// Realtime events: job.started and job.finished.
// Authorized by serverKey with scope widgetWrite.
func (c *AlphaClient) StartJob(ctx context.Context, input StartJobInput, opts ...CallOption) (*StartJobPayload, error) {
	var out *StartJobPayload
	err := c.t.call(ctx, "alpha.startJob", input, nil, &out, opts)
	return out, err
}

// Redeem calls the alpha.redeem mutation.
// Redeem a delivery with its permit.
//
// Idempotency: permitBound. Authorized by a single-use permit. Retry with the same requestId and permit.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by permit, sent as the permit argument without a bearer token.
func (c *AlphaClient) Redeem(ctx context.Context, permit string, input RedeemInput, opts ...CallOption) (*Receipt, error) {
	var out *Receipt
	err := c.t.call(ctx, "alpha.redeem", input, permit, &out, opts)
	return out, err
}

// BetaClient calls the beta plane.
// Widgets.
//
// Bearer credential: serverKey. Scoped key for server runtimes.
type BetaClient struct {
	t *transport
}

// Capabilities calls the beta.capabilities query.
// Read the server capabilities.
// Server capabilities.
//
// Idempotency: safe. Read-only. Repeat freely.
// Authorized by serverKey.
func (c *BetaClient) Capabilities(ctx context.Context, opts ...CallOption) (*Capabilities, error) {
	var out *Capabilities
	err := c.t.call(ctx, "beta.capabilities", nil, nil, &out, opts)
	return out, err
}

// ResolveRequest calls the beta.resolveRequest query.
// Look up the outcome of an earlier beta mutation by requestId.
//
// Idempotency: safe. Read-only. Repeat freely.
// Authorized by serverKey with scope widgetWrite.
func (c *BetaClient) ResolveRequest(ctx context.Context, input ResolveInput, opts ...CallOption) (*Receipt, error) {
	var out *Receipt
	err := c.t.call(ctx, "beta.resolveRequest", input, nil, &out, opts)
	return out, err
}

// Widgets calls the beta.widgets query.
// List widgets in one bounded page.
//
// Idempotency: safe. Read-only. Repeat freely.
// Pagination: bounded. One bounded page.
// Authorized by serverKey with scope itemRead.
func (c *BetaClient) Widgets(ctx context.Context, input *WidgetsInput, opts ...CallOption) (*WidgetsPayload, error) {
	var out *WidgetsPayload
	err := c.t.call(ctx, "beta.widgets", input, nil, &out, opts)
	return out, err
}

// CreateWidget calls the beta.createWidget mutation.
// Create a widget.
//
// Idempotency: singleUse. Like idempotent, but the result is good for one use.
// Retry budget: 2 attempts within 1 second.
// Authorized by serverKey with scope widgetWrite.
func (c *BetaClient) CreateWidget(ctx context.Context, input CreateWidgetInput, opts ...CallOption) (*Widget, error) {
	var out *Widget
	err := c.t.call(ctx, "beta.createWidget", input, nil, &out, opts)
	return out, err
}
