// Code generated by sdkgen. DO NOT EDIT.
// Run npm run generate:graphql to regenerate.

package convohop

// Blob is the GraphQL scalar Blob.
// Server-signed JSON object.
type Blob = map[string]any

// Counter is the GraphQL scalar Counter.
// Non-negative counter as a decimal string.
// Descriptions keep their line breaks, and a closing comment marker */ stays escaped.
type Counter = string

// Ratio is the GraphQL scalar Ratio.
// Fraction between 0 and 1.
type Ratio = float64

// Error codes reported in [Problem]. Classify errors by code, never by message text.
const (
	// The cursor is too old.
	// HTTP status 410. Not retryable. Raised by the server.
	ErrorCodeCursorExpired ErrorCode = "CURSOR_EXPIRED"
	// The request is malformed.
	// HTTP status 400. Not retryable. Raised by the server or the SDK.
	ErrorCodeInvalidRequest ErrorCode = "INVALID_REQUEST"
	// The resource does not exist.
	// HTTP status 404. Not retryable. Raised by the server.
	ErrorCodeNotFound ErrorCode = "NOT_FOUND"
	// The transport failed after sending.
	// Retryable. Raised by the SDK.
	ErrorCodeTransportUnknown ErrorCode = "TRANSPORT_UNKNOWN"
	// Temporarily unavailable.
	// HTTP status 503. Retryable. Raised by the server.
	ErrorCodeUnavailable ErrorCode = "UNAVAILABLE"
)

// Retryable reports whether the API documents the error code as retryable with the same request ID.
func (c ErrorCode) Retryable() bool {
	switch c {
	case ErrorCodeTransportUnknown,
		ErrorCodeUnavailable:
		return true
	}
	return false
}

// nonRetryable reports whether the API documents the error code as not retryable. Unlike
// !c.Retryable(), it is false for a code the API does not document.
func (c ErrorCode) nonRetryable() bool {
	switch c {
	case ErrorCodeCursorExpired,
		ErrorCodeInvalidRequest,
		ErrorCodeNotFound:
		return true
	}
	return false
}

// Capabilities is the GraphQL object Capabilities.
type Capabilities struct {
	Version  string   `json:"version"`
	WssURL   *string  `json:"wssUrl"`
	Features []string `json:"features"`
}

// CreateWidgetInput is the GraphQL input CreateWidgetInput.
type CreateWidgetInput struct {
	Label string `json:"label"`
	// Default: "ACTIVE".
	State *WidgetState `json:"state,omitzero"`
	// Default: 0.5.
	Ratio  *Ratio    `json:"ratio,omitzero"`
	Nested [][]int64 `json:"nested,omitzero"`
	// Default: {"kind":"box","sides":[1,2]}.
	Shape *ShapeInput `json:"shape,omitzero"`
}

// FetchInput is the GraphQL input FetchInput.
type FetchInput struct {
	// Default: "GET".
	Method *HTTPMethod `json:"method,omitzero"`
}

// HTTPMethod is the GraphQL enum HTTPMethod.
type HTTPMethod string

// HTTPMethod values.
const (
	HTTPMethodPost HTTPMethod = "POST"
	HTTPMethodGet  HTTPMethod = "GET"
)

// Job is the GraphQL object Job.
type Job struct {
	OperationID string   `json:"operationId"`
	State       string   `json:"state"`
	Progress    *float64 `json:"progress"`
	Output      Blob     `json:"output"`
}

// JobInput is the GraphQL input JobInput.
type JobInput struct {
	OperationID string `json:"operationId"`
}

// JobRef is the GraphQL object JobRef.
type JobRef struct {
	OperationID string `json:"operationId"`
	State       string `json:"state"`
}

// Receipt is the GraphQL object Receipt.
type Receipt struct {
	RequestID string   `json:"requestId"`
	Committed bool     `json:"committed"`
	Sequence  *Counter `json:"sequence"`
}

// RedeemInput is the GraphQL input RedeemInput.
type RedeemInput struct {
	DeliveryID string `json:"deliveryId"`
}

// ResolveInput is the GraphQL input ResolveInput.
type ResolveInput struct {
	RequestID string `json:"requestId"`
}

// ShapeInput is the GraphQL input ShapeInput.
type ShapeInput struct {
	Kind  string  `json:"kind"`
	Sides []int64 `json:"sides"`
}

// StartJobInput is the GraphQL input StartJobInput.
type StartJobInput struct {
	ItemID string `json:"itemId"`
	// How many times to run.
	// Default: 1.
	Repeat *int64 `json:"repeat,omitzero"`
	Props  Blob   `json:"props,omitzero"`
}

// StartJobPayload is the GraphQL object StartJobPayload.
type StartJobPayload struct {
	RequestID string  `json:"requestId"`
	Receipt   Receipt `json:"receipt"`
	Job       *JobRef `json:"job"`
}

// Widget is the GraphQL object Widget.
type Widget struct {
	ID       string      `json:"id"`
	Label    *string     `json:"label"`
	State    WidgetState `json:"state"`
	Revision Counter     `json:"revision"`
}

// WidgetPage is the GraphQL object WidgetPage.
type WidgetPage struct {
	Items           []Widget `json:"items"`
	Complete        bool     `json:"complete"`
	RefreshRequired bool     `json:"refreshRequired"`
}

// WidgetState is the GraphQL enum WidgetState.
type WidgetState string

// WidgetState values.
const (
	WidgetStateActive   WidgetState = "ACTIVE"
	WidgetStateArchived WidgetState = "ARCHIVED"
)

// WidgetsInput is the GraphQL input WidgetsInput.
type WidgetsInput struct {
	States []WidgetState `json:"states,omitzero"`
}

// WidgetsPayload is the GraphQL object WidgetsPayload.
type WidgetsPayload struct {
	RequestID string      `json:"requestId"`
	Result    *WidgetPage `json:"result"`
}
