// Code generated by sdkgen. DO NOT EDIT.
// Run npm run generate:graphql to regenerate.

package convohop

import (
	"context"
	"iter"
)

// ProjectClient calls the communication plane.
// Conversations, members, messages, receipts, realtime events and live sessions inside one project.
//
// Bearer credential: backendKey. Scoped project backend key. Server runtimes only; never ship it to clients.
// Context credential: deliveryPermit. Signed permit from management.credentialPermit, sent in the request context of a request without a bearer token.
type ProjectClient struct {
	t *transport
}

// Capabilities calls the communication.capabilities query.
// Describe the features, limits and API model the authority supports.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by backendKey.
func (c *ProjectClient) Capabilities(ctx context.Context, opts ...CallOption) (*CapabilitiesReply, error) {
	var out *CapabilitiesReply
	err := c.t.call(ctx, "communication.capabilities", nil, nil, &out, opts)
	return out, err
}

// Route calls the communication.route query.
// Return the signed route: project incarnation, serving epoch and realtime endpoint. Call it before other communication operations and again after WRONG_REGION.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by backendKey.
func (c *ProjectClient) Route(ctx context.Context, opts ...CallOption) (*RouteReply, error) {
	var out *RouteReply
	err := c.t.call(ctx, "communication.route", nil, nil, &out, opts)
	return out, err
}

// GetPrincipal calls the communication.getPrincipal query.
// Read a principal (an application user).
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by backendKey with scope principalManage.
func (c *ProjectClient) GetPrincipal(ctx context.Context, input GetPrincipalRequestInput, opts ...CallOption) (*GetPrincipalReply, error) {
	var out *GetPrincipalReply
	err := c.t.call(ctx, "communication.getPrincipal", input, nil, &out, opts)
	return out, err
}

// GetConversation calls the communication.getConversation query.
// Read a conversation.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by backendKey with scope conversationManage.
func (c *ProjectClient) GetConversation(ctx context.Context, input GetConversationRequestInput, opts ...CallOption) (*GetConversationReply, error) {
	var out *GetConversationReply
	err := c.t.call(ctx, "communication.getConversation", input, nil, &out, opts)
	return out, err
}

// Members calls the communication.members query.
// List the members of a conversation.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Pagination: cursor. Server-ordered pages. Pass nextCursor back as the cursor input until complete is true. [ProjectClient.MembersPages] iterates over the pages.
// Authorized by backendKey with scope membershipManage.
func (c *ProjectClient) Members(ctx context.Context, input MembersRequestInput, opts ...CallOption) (*MembersReply, error) {
	var out *MembersReply
	err := c.t.call(ctx, "communication.members", input, nil, &out, opts)
	return out, err
}

// MembersPages iterates over the pages of [ProjectClient.Members], starting at input.Cursor.
// Each page is a new request with a new request ID.
// Iteration stops after the complete page or at the first error.
// A page that requires a refresh yields [ErrRefreshRequired] and stops.
// An incomplete page whose next cursor is missing, malformed or doesn't advance yields an INVALID_RESPONSE [Problem] in place of the page and stops.
func (c *ProjectClient) MembersPages(ctx context.Context, input MembersRequestInput) iter.Seq2[*MemberPage, error] {
	return paginate(input.Cursor, pageCursor{"String", serverOrder}, func(cursor *string) (*MemberPage, pageState, error) {
		request := input
		request.Cursor = cursor
		out, err := c.Members(ctx, request)
		if err != nil {
			return nil, pageState{}, err
		}
		if out.Result == nil {
			return nil, pageState{}, missingPage()
		}
		page := out.Result
		return page, pageState{page.Complete, page.RefreshRequired, page.NextCursor}, nil
	})
}

// Messages calls the communication.messages query.
// List the messages of a conversation, newest first. A backend key reads the full history, or the history visible to the member named by actAsPrincipalId.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Pagination: sequence. Newest first. Pass nextCursor back as the sequence cursor input to read older items until complete is true. [ProjectClient.MessagesPages] iterates over the pages.
// Authorized by backendKey with scope messageRead.
func (c *ProjectClient) Messages(ctx context.Context, input MessagesRequestInput, opts ...CallOption) (*MessagesReply, error) {
	var out *MessagesReply
	err := c.t.call(ctx, "communication.messages", input, nil, &out, opts)
	return out, err
}

// MessagesPages iterates over the pages of [ProjectClient.Messages], starting at input.BeforeSequence.
// Each page is a new request with a new request ID.
// Iteration stops after the complete page or at the first error.
// A page that requires a refresh yields [ErrRefreshRequired] and stops.
// An incomplete page whose next cursor is missing, malformed or doesn't advance yields an INVALID_RESPONSE [Problem] in place of the page and stops.
func (c *ProjectClient) MessagesPages(ctx context.Context, input MessagesRequestInput) iter.Seq2[*MessagePage, error] {
	return paginate(input.BeforeSequence, pageCursor{"Decimal", descendingOrder}, func(cursor *string) (*MessagePage, pageState, error) {
		request := input
		request.BeforeSequence = cursor
		out, err := c.Messages(ctx, request)
		if err != nil {
			return nil, pageState{}, err
		}
		if out.Result == nil {
			return nil, pageState{}, missingPage()
		}
		page := out.Result
		return page, pageState{page.Complete, page.RefreshRequired, page.NextCursor}, nil
	})
}

// GetMessage calls the communication.getMessage query.
// Read one message. A backend key reads any message, or reads as the member named by actAsPrincipalId.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by backendKey with scope messageRead.
func (c *ProjectClient) GetMessage(ctx context.Context, input GetMessageRequestInput, opts ...CallOption) (*GetMessageReply, error) {
	var out *GetMessageReply
	err := c.t.call(ctx, "communication.getMessage", input, nil, &out, opts)
	return out, err
}

// Inbox calls the communication.inbox query.
// List the conversations visible to the calling user. A backend key must name that user with actAsPrincipalId.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Pagination: cursor. Server-ordered pages. Pass nextCursor back as the cursor input until complete is true. [ProjectClient.InboxPages] iterates over the pages.
// Authorized by backendKey with scope messageRead.
func (c *ProjectClient) Inbox(ctx context.Context, input InboxRequestInput, opts ...CallOption) (*InboxReply, error) {
	var out *InboxReply
	err := c.t.call(ctx, "communication.inbox", input, nil, &out, opts)
	return out, err
}

// InboxPages iterates over the pages of [ProjectClient.Inbox], starting at input.Cursor.
// Each page is a new request with a new request ID.
// Iteration stops after the complete page or at the first error.
// A page that requires a refresh yields [ErrRefreshRequired] and stops.
// An incomplete page whose next cursor is missing, malformed or doesn't advance yields an INVALID_RESPONSE [Problem] in place of the page and stops.
func (c *ProjectClient) InboxPages(ctx context.Context, input InboxRequestInput) iter.Seq2[*InboxPage, error] {
	return paginate(input.Cursor, pageCursor{"String", serverOrder}, func(cursor *string) (*InboxPage, pageState, error) {
		request := input
		request.Cursor = cursor
		out, err := c.Inbox(ctx, request)
		if err != nil {
			return nil, pageState{}, err
		}
		if out.Result == nil {
			return nil, pageState{}, missingPage()
		}
		page := out.Result
		return page, pageState{page.Complete, page.RefreshRequired, page.NextCursor}, nil
	})
}

// Search calls the communication.search query.
// Search the messages visible to the calling user. A backend key searches as the member named by actAsPrincipalId, or within scope.conversationIds.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Pagination: cursor. Server-ordered pages. Pass nextCursor back as the cursor input until complete is true. [ProjectClient.SearchPages] iterates over the pages.
// Authorized by backendKey with scope messageRead.
func (c *ProjectClient) Search(ctx context.Context, input SearchRequestInput, opts ...CallOption) (*SearchReply, error) {
	var out *SearchReply
	err := c.t.call(ctx, "communication.search", input, nil, &out, opts)
	return out, err
}

// SearchPages iterates over the pages of [ProjectClient.Search], starting at input.Cursor.
// Each page is a new request with a new request ID.
// Iteration stops after the complete page or at the first error.
// A page that requires a refresh yields [ErrRefreshRequired] and stops.
// An incomplete page whose next cursor is missing, malformed or doesn't advance yields an INVALID_RESPONSE [Problem] in place of the page and stops.
func (c *ProjectClient) SearchPages(ctx context.Context, input SearchRequestInput) iter.Seq2[*SearchPage, error] {
	return paginate(input.Cursor, pageCursor{"String", serverOrder}, func(cursor *string) (*SearchPage, pageState, error) {
		request := input
		request.Cursor = cursor
		out, err := c.Search(ctx, request)
		if err != nil {
			return nil, pageState{}, err
		}
		if out.Result == nil {
			return nil, pageState{}, missingPage()
		}
		page := out.Result
		return page, pageState{page.Complete, page.RefreshRequired, page.NextCursor}, nil
	})
}

// ResolveRequest calls the communication.resolveRequest query.
// Look up the stored outcome of an earlier communication mutation by its requestId.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by backendKey (condition: ownRequest).
func (c *ProjectClient) ResolveRequest(ctx context.Context, input ResolveRequestRequestInput, opts ...CallOption) (*ResolveRequestReply, error) {
	var out *ResolveRequestReply
	err := c.t.call(ctx, "communication.resolveRequest", input, nil, &out, opts)
	return out, err
}

// GetOperation calls the communication.getOperation query.
// Read the state of a long-running communication operation.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by backendKey (condition: operationParticipant).
func (c *ProjectClient) GetOperation(ctx context.Context, input GetOperationRequestInput, opts ...CallOption) (*GetOperationReply, error) {
	var out *GetOperationReply
	err := c.t.call(ctx, "communication.getOperation", input, nil, &out, opts)
	return out, err
}

// ConversationMute calls the communication.conversationMute query.
// Read whether a member has muted message push notifications for a conversation. A backend key must name the member with actAsPrincipalId.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by backendKey with scope membershipManage.
func (c *ProjectClient) ConversationMute(ctx context.Context, input ConversationMuteInput, opts ...CallOption) (*ConversationMuteReply, error) {
	var out *ConversationMuteReply
	err := c.t.call(ctx, "communication.conversationMute", input, nil, &out, opts)
	return out, err
}

// CurrentLiveSession calls the communication.currentLiveSession query.
// Return the active live session of a conversation, if any.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by any one of: backendKey with scope callRead; backendKey with scope callManage.
func (c *ProjectClient) CurrentLiveSession(ctx context.Context, input ConversationLiveInput, opts ...CallOption) (*CurrentLiveSessionReply, error) {
	var out *CurrentLiveSessionReply
	err := c.t.call(ctx, "communication.currentLiveSession", input, nil, &out, opts)
	return out, err
}

// LiveSession calls the communication.liveSession query.
// Read a live session.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by any one of: backendKey with scope callRead; backendKey with scope callManage.
func (c *ProjectClient) LiveSession(ctx context.Context, input LiveSessionInput, opts ...CallOption) (*LiveSessionReply, error) {
	var out *LiveSessionReply
	err := c.t.call(ctx, "communication.liveSession", input, nil, &out, opts)
	return out, err
}

// LiveSessions calls the communication.liveSessions query.
// List the live sessions of a conversation.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Pagination: cursor. Server-ordered pages. Pass nextCursor back as the cursor input until complete is true. [ProjectClient.LiveSessionsPages] iterates over the pages.
// Authorized by any one of: backendKey with scope callRead; backendKey with scope callManage.
func (c *ProjectClient) LiveSessions(ctx context.Context, input LiveSessionsInput, opts ...CallOption) (*LiveSessionPageReply, error) {
	var out *LiveSessionPageReply
	err := c.t.call(ctx, "communication.liveSessions", input, nil, &out, opts)
	return out, err
}

// LiveSessionsPages iterates over the pages of [ProjectClient.LiveSessions], starting at input.Cursor.
// Each page is a new request with a new request ID.
// Iteration stops after the complete page or at the first error.
// A page that requires a refresh yields [ErrRefreshRequired] and stops.
// An incomplete page whose next cursor is missing, malformed or doesn't advance yields an INVALID_RESPONSE [Problem] in place of the page and stops.
func (c *ProjectClient) LiveSessionsPages(ctx context.Context, input LiveSessionsInput) iter.Seq2[*LiveSessionPage, error] {
	return paginate(input.Cursor, pageCursor{"String", serverOrder}, func(cursor *string) (*LiveSessionPage, pageState, error) {
		request := input
		request.Cursor = cursor
		out, err := c.LiveSessions(ctx, request)
		if err != nil {
			return nil, pageState{}, err
		}
		page := &out.Result
		return page, pageState{page.Complete, page.RefreshRequired, page.NextCursor}, nil
	})
}

// LiveSessionParticipants calls the communication.liveSessionParticipants query.
// List the participants of a live session.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Pagination: cursor. Server-ordered pages. Pass nextCursor back as the cursor input until complete is true. [ProjectClient.LiveSessionParticipantsPages] iterates over the pages.
// Authorized by any one of: backendKey with scope callRead; backendKey with scope callManage.
func (c *ProjectClient) LiveSessionParticipants(ctx context.Context, input LiveParticipantsInput, opts ...CallOption) (*LiveParticipantPageReply, error) {
	var out *LiveParticipantPageReply
	err := c.t.call(ctx, "communication.liveSessionParticipants", input, nil, &out, opts)
	return out, err
}

// LiveSessionParticipantsPages iterates over the pages of [ProjectClient.LiveSessionParticipants], starting at input.Cursor.
// Each page is a new request with a new request ID.
// Iteration stops after the complete page or at the first error.
// A page that requires a refresh yields [ErrRefreshRequired] and stops.
// An incomplete page whose next cursor is missing, malformed or doesn't advance yields an INVALID_RESPONSE [Problem] in place of the page and stops.
func (c *ProjectClient) LiveSessionParticipantsPages(ctx context.Context, input LiveParticipantsInput) iter.Seq2[*LiveParticipantPage, error] {
	return paginate(input.Cursor, pageCursor{"String", serverOrder}, func(cursor *string) (*LiveParticipantPage, pageState, error) {
		request := input
		request.Cursor = cursor
		out, err := c.LiveSessionParticipants(ctx, request)
		if err != nil {
			return nil, pageState{}, err
		}
		page := &out.Result
		return page, pageState{page.Complete, page.RefreshRequired, page.NextCursor}, nil
	})
}

// LiveSessionOperation calls the communication.liveSessionOperation query.
// Read the state of a live session start or end operation.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by any one of: backendKey with scope callRead; backendKey with scope callManage.
func (c *ProjectClient) LiveSessionOperation(ctx context.Context, input LiveSessionOperationInput, opts ...CallOption) (*LiveSessionOperationReply, error) {
	var out *LiveSessionOperationReply
	err := c.t.call(ctx, "communication.liveSessionOperation", input, nil, &out, opts)
	return out, err
}

// SessionRequestOutcome calls the communication.sessionRequestOutcome query.
// Look up the outcome of an earlier issueSession or renewSession request, including the session it produced.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by backendKey with all of the scopes sessionIssue and sessionManage.
func (c *ProjectClient) SessionRequestOutcome(ctx context.Context, input SessionRequestOutcomeRequestInput, opts ...CallOption) (*SessionRequestOutcomeReply, error) {
	var out *SessionRequestOutcomeReply
	err := c.t.call(ctx, "communication.sessionRequestOutcome", input, nil, &out, opts)
	return out, err
}

// CreatePrincipal calls the communication.createPrincipal mutation.
// Create a principal for an application user.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by backendKey with scope principalManage.
func (c *ProjectClient) CreatePrincipal(ctx context.Context, input CreatePrincipalRequestInput, opts ...CallOption) (*CreatePrincipalReply, error) {
	var out *CreatePrincipalReply
	err := c.t.call(ctx, "communication.createPrincipal", input, nil, &out, opts)
	return out, err
}

// DisablePrincipal calls the communication.disablePrincipal mutation.
// Disable a principal.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by backendKey with scope principalManage.
func (c *ProjectClient) DisablePrincipal(ctx context.Context, input DisablePrincipalRequestInput, opts ...CallOption) (*DisablePrincipalReply, error) {
	var out *DisablePrincipalReply
	err := c.t.call(ctx, "communication.disablePrincipal", input, nil, &out, opts)
	return out, err
}

// IssueSession calls the communication.issueSession mutation.
// Issue a short-lived user session token for a principal and device.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by backendKey with scope sessionIssue.
func (c *ProjectClient) IssueSession(ctx context.Context, input IssueSessionRequestInput, opts ...CallOption) (*IssueSessionReply, error) {
	var out *IssueSessionReply
	err := c.t.call(ctx, "communication.issueSession", input, nil, &out, opts)
	return out, err
}

// RenewSession calls the communication.renewSession mutation.
// Renew a user session before it expires.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by backendKey with scope sessionIssue.
func (c *ProjectClient) RenewSession(ctx context.Context, input RenewSessionRequestInput, opts ...CallOption) (*RenewSessionReply, error) {
	var out *RenewSessionReply
	err := c.t.call(ctx, "communication.renewSession", input, nil, &out, opts)
	return out, err
}

// RevokeSession calls the communication.revokeSession mutation.
// Revoke a user session.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by backendKey with scope sessionManage.
func (c *ProjectClient) RevokeSession(ctx context.Context, input RevokeSessionRequestInput, opts ...CallOption) (*RevokeSessionReply, error) {
	var out *RevokeSessionReply
	err := c.t.call(ctx, "communication.revokeSession", input, nil, &out, opts)
	return out, err
}

// CreateConversation calls the communication.createConversation mutation.
// Create a conversation with its initial members.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Realtime events: conversation.created.
// Authorized by backendKey with scope conversationManage.
func (c *ProjectClient) CreateConversation(ctx context.Context, input CreateConversationRequestInput, opts ...CallOption) (*CreateConversationReply, error) {
	var out *CreateConversationReply
	err := c.t.call(ctx, "communication.createConversation", input, nil, &out, opts)
	return out, err
}

// UpdateConversation calls the communication.updateConversation mutation.
// Update the title or properties of a conversation.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Realtime events: conversation.updated.
// Authorized by backendKey with scope conversationManage.
func (c *ProjectClient) UpdateConversation(ctx context.Context, input UpdateConversationRequestInput, opts ...CallOption) (*UpdateConversationReply, error) {
	var out *UpdateConversationReply
	err := c.t.call(ctx, "communication.updateConversation", input, nil, &out, opts)
	return out, err
}

// AddMember calls the communication.addMember mutation.
// Add a member, or change the role of an active member.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Realtime events: member.added and member.roleChanged.
// Authorized by backendKey with scope membershipManage.
func (c *ProjectClient) AddMember(ctx context.Context, input AddMemberRequestInput, opts ...CallOption) (*AddMemberReply, error) {
	var out *AddMemberReply
	err := c.t.call(ctx, "communication.addMember", input, nil, &out, opts)
	return out, err
}

// AddMembers calls the communication.addMembers mutation.
// Add several members in one request.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Realtime events: member.added and member.roleChanged.
// Authorized by backendKey with scope membershipManage.
func (c *ProjectClient) AddMembers(ctx context.Context, input AddMembersInput, opts ...CallOption) (*AddMembersPayload, error) {
	var out *AddMembersPayload
	err := c.t.call(ctx, "communication.addMembers", input, nil, &out, opts)
	return out, err
}

// RemoveMember calls the communication.removeMember mutation.
// Remove a member from a conversation.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Realtime events: member.removed.
// Authorized by backendKey with scope membershipManage.
func (c *ProjectClient) RemoveMember(ctx context.Context, input RemoveMemberRequestInput, opts ...CallOption) (*RemoveMemberReply, error) {
	var out *RemoveMemberReply
	err := c.t.call(ctx, "communication.removeMember", input, nil, &out, opts)
	return out, err
}

// HistoryGrant calls the communication.historyGrant mutation.
// Expand the history a member can see to an earlier sequence.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Realtime events: member.historyExpanded.
// Authorized by backendKey with scope historyManage.
func (c *ProjectClient) HistoryGrant(ctx context.Context, input HistoryGrantRequestInput, opts ...CallOption) (*HistoryGrantReply, error) {
	var out *HistoryGrantReply
	err := c.t.call(ctx, "communication.historyGrant", input, nil, &out, opts)
	return out, err
}

// SendMessage calls the communication.sendMessage mutation.
// Send a message. A backend key sends as its service principal, or as the member named by actAsPrincipalId.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Realtime events: message.created.
// Authorized by backendKey with scope messageWrite.
func (c *ProjectClient) SendMessage(ctx context.Context, input SendMessageRequestInput, opts ...CallOption) (*SendMessageReply, error) {
	var out *SendMessageReply
	err := c.t.call(ctx, "communication.sendMessage", input, nil, &out, opts)
	return out, err
}

// EditMessage calls the communication.editMessage mutation.
// Edit a message.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Realtime events: message.edited.
// Authorized by backendKey with scope moderation.
func (c *ProjectClient) EditMessage(ctx context.Context, input EditMessageRequestInput, opts ...CallOption) (*EditMessageReply, error) {
	var out *EditMessageReply
	err := c.t.call(ctx, "communication.editMessage", input, nil, &out, opts)
	return out, err
}

// DeleteMessage calls the communication.deleteMessage mutation.
// Delete a message.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Realtime events: message.deleted.
// Authorized by backendKey with scope moderation.
func (c *ProjectClient) DeleteMessage(ctx context.Context, input DeleteMessageRequestInput, opts ...CallOption) (*DeleteMessageReply, error) {
	var out *DeleteMessageReply
	err := c.t.call(ctx, "communication.deleteMessage", input, nil, &out, opts)
	return out, err
}

// SetBroadcastPermission calls the communication.setBroadcastPermission mutation.
// Allow or deny a member to publish media in live sessions.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Realtime events: member.broadcastPermissionChanged.
// Authorized by backendKey with scope membershipManage.
func (c *ProjectClient) SetBroadcastPermission(ctx context.Context, input SetBroadcastPermissionInput, opts ...CallOption) (*SetBroadcastPermissionPayload, error) {
	var out *SetBroadcastPermissionPayload
	err := c.t.call(ctx, "communication.setBroadcastPermission", input, nil, &out, opts)
	return out, err
}

// SetConversationMute calls the communication.setConversationMute mutation.
// Mute or unmute message push notifications for a member of a conversation, optionally until a time. Calls still ring. A backend key must name the member with actAsPrincipalId.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by backendKey with scope membershipManage.
func (c *ProjectClient) SetConversationMute(ctx context.Context, input SetConversationMuteInput, opts ...CallOption) (*SetConversationMutePayload, error) {
	var out *SetConversationMutePayload
	err := c.t.call(ctx, "communication.setConversationMute", input, nil, &out, opts)
	return out, err
}

// AlertLiveSession calls the communication.alertLiveSession mutation.
// Alert (ring) conversation members about a live session.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Realtime events: live.alerted.
// Authorized by backendKey with scope callManage.
func (c *ProjectClient) AlertLiveSession(ctx context.Context, input AlertLiveSessionInput, opts ...CallOption) (*AlertLiveSessionPayload, error) {
	var out *AlertLiveSessionPayload
	err := c.t.call(ctx, "communication.alertLiveSession", input, nil, &out, opts)
	return out, err
}

// EndLiveSession calls the communication.endLiveSession mutation.
// End a live session for every participant. Completes asynchronously.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Long-running: poll [ProjectClient.LiveSessionOperation] with the operation reference from the result until the work completes.
// Realtime events: live.ended.
// Authorized by backendKey with scope callManage.
func (c *ProjectClient) EndLiveSession(ctx context.Context, input EndLiveSessionInput, opts ...CallOption) (*EndLiveSessionPayload, error) {
	var out *EndLiveSessionPayload
	err := c.t.call(ctx, "communication.endLiveSession", input, nil, &out, opts)
	return out, err
}

// RedeemCredential calls the communication.redeemCredential mutation.
// Redeem a delivered credential with its delivery permit.
//
// Idempotency: permitBound. Authorized by a single-delivery permit. Retry with the same requestId and permit; outcomes cannot be resolved by lookup.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by deliveryPermit, sent as the permit argument without a bearer token.
func (c *ProjectClient) RedeemCredential(ctx context.Context, permit SignedProof, input RedeemCredentialRequestInput, opts ...CallOption) (*RedeemCredentialReply, error) {
	var out *RedeemCredentialReply
	err := c.t.call(ctx, "communication.redeemCredential", input, permit, &out, opts)
	return out, err
}

// AcknowledgeCredential calls the communication.acknowledgeCredential mutation.
// Acknowledge that a redeemed credential is stored, closing the delivery.
//
// Idempotency: permitBound. Authorized by a single-delivery permit. Retry with the same requestId and permit; outcomes cannot be resolved by lookup.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by deliveryPermit, sent as the permit argument without a bearer token.
func (c *ProjectClient) AcknowledgeCredential(ctx context.Context, permit SignedProof, input AcknowledgeCredentialRequestInput, opts ...CallOption) (*AcknowledgeCredentialReply, error) {
	var out *AcknowledgeCredentialReply
	err := c.t.call(ctx, "communication.acknowledgeCredential", input, permit, &out, opts)
	return out, err
}

// ManagementClient calls the management plane.
// Organizations, deployments, projects, backend keys and webhooks.
//
// Bearer credential: portalCredential. Operator credential for the management plane. Server runtimes only.
type ManagementClient struct {
	t *transport
}

// Capabilities calls the management.capabilities query.
// Describe the management features and limits the authority supports.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by portalCredential.
func (c *ManagementClient) Capabilities(ctx context.Context, opts ...CallOption) (*CapabilitiesReply, error) {
	var out *CapabilitiesReply
	err := c.t.call(ctx, "management.capabilities", nil, nil, &out, opts)
	return out, err
}

// Organizations calls the management.organizations query.
// List the organizations the caller can access.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Pagination: bounded. One bounded page without a cursor input. complete reports whether every item fit.
// Authorized by portalCredential.
func (c *ManagementClient) Organizations(ctx context.Context, opts ...CallOption) (*OrganizationsReply, error) {
	var out *OrganizationsReply
	err := c.t.call(ctx, "management.organizations", nil, nil, &out, opts)
	return out, err
}

// GetOrganization calls the management.getOrganization query.
// Read an organization.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) GetOrganization(ctx context.Context, input GetOrganizationRequestInput, opts ...CallOption) (*GetOrganizationReply, error) {
	var out *GetOrganizationReply
	err := c.t.call(ctx, "management.getOrganization", input, nil, &out, opts)
	return out, err
}

// GetDeployment calls the management.getDeployment query.
// Read a deployment.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) GetDeployment(ctx context.Context, input GetDeploymentRequestInput, opts ...CallOption) (*GetDeploymentReply, error) {
	var out *GetDeploymentReply
	err := c.t.call(ctx, "management.getDeployment", input, nil, &out, opts)
	return out, err
}

// GetProject calls the management.getProject query.
// Read a project.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) GetProject(ctx context.Context, input GetProjectRequestInput, opts ...CallOption) (*GetProjectReply, error) {
	var out *GetProjectReply
	err := c.t.call(ctx, "management.getProject", input, nil, &out, opts)
	return out, err
}

// DeploymentHealth calls the management.deploymentHealth query.
// Read the health of a deployment.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) DeploymentHealth(ctx context.Context, input DeploymentHealthRequestInput, opts ...CallOption) (*DeploymentHealthReply, error) {
	var out *DeploymentHealthReply
	err := c.t.call(ctx, "management.deploymentHealth", input, nil, &out, opts)
	return out, err
}

// DeploymentUsage calls the management.deploymentUsage query.
// Read the metered usage of a deployment, summed over its projects. The range defaults to the current UTC month to date, both bounds round up to whole UTC hours, and it spans at most 400 days.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) DeploymentUsage(ctx context.Context, input DeploymentUsageRequestInput, opts ...CallOption) (*DeploymentUsageReply, error) {
	var out *DeploymentUsageReply
	err := c.t.call(ctx, "management.deploymentUsage", input, nil, &out, opts)
	return out, err
}

// ProjectUsage calls the management.projectUsage query.
// Read the metered usage of a project. The range defaults to the current UTC month to date, both bounds round up to whole UTC hours, and it spans at most 400 days.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) ProjectUsage(ctx context.Context, input ProjectUsageRequestInput, opts ...CallOption) (*ProjectUsageReply, error) {
	var out *ProjectUsageReply
	err := c.t.call(ctx, "management.projectUsage", input, nil, &out, opts)
	return out, err
}

// OrganizationUsage calls the management.organizationUsage query.
// Read the metered usage of an organization in any status, summed over its projects. The range defaults to the current UTC month to date, both bounds round up to whole UTC hours, and it spans at most 400 days.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) OrganizationUsage(ctx context.Context, input OrganizationUsageRequestInput, opts ...CallOption) (*OrganizationUsageReply, error) {
	var out *OrganizationUsageReply
	err := c.t.call(ctx, "management.organizationUsage", input, nil, &out, opts)
	return out, err
}

// OrganizationBilling calls the management.organizationBilling query.
// Read the billing state of an organization in any status: the plan whose limits apply, whether ConvoHop bills the organization and, when it does, its standing and subscription.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) OrganizationBilling(ctx context.Context, input OrganizationBillingRequestInput, opts ...CallOption) (*OrganizationBillingReply, error) {
	var out *OrganizationBillingReply
	err := c.t.call(ctx, "management.organizationBilling", input, nil, &out, opts)
	return out, err
}

// WebhookEndpoints calls the management.webhookEndpoints query.
// List the webhook endpoints of a project with their status, signing-secret rotation and delivery health.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Pagination: bounded. One bounded page without a cursor input. complete reports whether every item fit.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) WebhookEndpoints(ctx context.Context, input WebhookEndpointsRequestInput, opts ...CallOption) (*WebhookEndpointsReply, error) {
	var out *WebhookEndpointsReply
	err := c.t.call(ctx, "management.webhookEndpoints", input, nil, &out, opts)
	return out, err
}

// WebhookDeliveries calls the management.webhookDeliveries query.
// List recent deliveries of a webhook endpoint.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Pagination: bounded. One bounded page without a cursor input. complete reports whether every item fit.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) WebhookDeliveries(ctx context.Context, input WebhookDeliveriesRequestInput, opts ...CallOption) (*WebhookDeliveriesReply, error) {
	var out *WebhookDeliveriesReply
	err := c.t.call(ctx, "management.webhookDeliveries", input, nil, &out, opts)
	return out, err
}

// ResolveRequest calls the management.resolveRequest query.
// Look up the stored outcome of an earlier management mutation by its requestId.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by portalCredential (condition: ownRequest).
func (c *ManagementClient) ResolveRequest(ctx context.Context, input ResolveRequestRequestInput, opts ...CallOption) (*ResolveRequestReply, error) {
	var out *ResolveRequestReply
	err := c.t.call(ctx, "management.resolveRequest", input, nil, &out, opts)
	return out, err
}

// GetOperation calls the management.getOperation query.
// Read the state of a long-running management operation.
//
// Idempotency: safe. Read-only. Repeat freely; each attempt may use a new requestId.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) GetOperation(ctx context.Context, input GetOperationRequestInput, opts ...CallOption) (*GetOperationReply, error) {
	var out *GetOperationReply
	err := c.t.call(ctx, "management.getOperation", input, nil, &out, opts)
	return out, err
}

// CreateOrganization calls the management.createOrganization mutation.
// Create an organization.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by portalCredential.
func (c *ManagementClient) CreateOrganization(ctx context.Context, input CreateOrganizationRequestInput, opts ...CallOption) (*CreateOrganizationReply, error) {
	var out *CreateOrganizationReply
	err := c.t.call(ctx, "management.createOrganization", input, nil, &out, opts)
	return out, err
}

// CreateDeployment calls the management.createDeployment mutation.
// Create a deployment in an organization. Completes asynchronously.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Long-running: poll [ManagementClient.GetOperation] with the operation reference from the result until the work completes.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) CreateDeployment(ctx context.Context, input CreateDeploymentRequestInput, opts ...CallOption) (*CreateDeploymentReply, error) {
	var out *CreateDeploymentReply
	err := c.t.call(ctx, "management.createDeployment", input, nil, &out, opts)
	return out, err
}

// CreateProject calls the management.createProject mutation.
// Create a project in a ready deployment. Completes asynchronously.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Long-running: poll [ManagementClient.GetOperation] with the operation reference from the result until the work completes.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) CreateProject(ctx context.Context, input CreateProjectRequestInput, opts ...CallOption) (*CreateProjectReply, error) {
	var out *CreateProjectReply
	err := c.t.call(ctx, "management.createProject", input, nil, &out, opts)
	return out, err
}

// IssueBackendKey calls the management.issueBackendKey mutation.
// Issue a scoped backend key. The secret is delivered once through a credential delivery.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Long-running: poll [ManagementClient.GetOperation] with the operation reference from the result until the work completes.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) IssueBackendKey(ctx context.Context, input IssueBackendKeyRequestInput, opts ...CallOption) (*IssueBackendKeyReply, error) {
	var out *IssueBackendKeyReply
	err := c.t.call(ctx, "management.issueBackendKey", input, nil, &out, opts)
	return out, err
}

// RevokeBackendKey calls the management.revokeBackendKey mutation.
// Revoke a backend key, optionally revoking the sessions it issued.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Long-running: poll [ManagementClient.GetOperation] with the operation reference from the result until the work completes.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) RevokeBackendKey(ctx context.Context, input RevokeBackendKeyRequestInput, opts ...CallOption) (*RevokeBackendKeyReply, error) {
	var out *RevokeBackendKeyReply
	err := c.t.call(ctx, "management.revokeBackendKey", input, nil, &out, opts)
	return out, err
}

// ProjectPolicy calls the management.projectPolicy mutation.
// Change the policy of a project.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Long-running: poll [ManagementClient.GetOperation] with the operation reference from the result until the work completes.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) ProjectPolicy(ctx context.Context, input ProjectPolicyRequestInput, opts ...CallOption) (*ProjectPolicyReply, error) {
	var out *ProjectPolicyReply
	err := c.t.call(ctx, "management.projectPolicy", input, nil, &out, opts)
	return out, err
}

// CredentialPermit calls the management.credentialPermit mutation.
// Issue a signed permit that authorizes redeeming one credential delivery.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) CredentialPermit(ctx context.Context, input CredentialPermitRequestInput, opts ...CallOption) (*CredentialPermitReply, error) {
	var out *CredentialPermitReply
	err := c.t.call(ctx, "management.credentialPermit", input, nil, &out, opts)
	return out, err
}

// PauseOperation calls the management.pauseOperation mutation.
// Pause a long-running operation.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) PauseOperation(ctx context.Context, input PauseOperationRequestInput, opts ...CallOption) (*PauseOperationReply, error) {
	var out *PauseOperationReply
	err := c.t.call(ctx, "management.pauseOperation", input, nil, &out, opts)
	return out, err
}

// ResumeOperation calls the management.resumeOperation mutation.
// Resume a paused operation.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) ResumeOperation(ctx context.Context, input ResumeOperationRequestInput, opts ...CallOption) (*ResumeOperationReply, error) {
	var out *ResumeOperationReply
	err := c.t.call(ctx, "management.resumeOperation", input, nil, &out, opts)
	return out, err
}

// CreateBillingCheckoutSession calls the management.createBillingCheckoutSession mutation.
// Create a hosted checkout link that subscribes an active organization to a self-service plan. The link grants access to whoever holds it; a retry with the same requestId returns the same link until it expires.
//
// Idempotency: singleUse. Like idempotent, but the result carries a short-lived credential for one connection. Request a new one instead of reusing an expired result.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) CreateBillingCheckoutSession(ctx context.Context, input CreateBillingCheckoutSessionRequestInput, opts ...CallOption) (*CreateBillingCheckoutSessionReply, error) {
	var out *CreateBillingCheckoutSessionReply
	err := c.t.call(ctx, "management.createBillingCheckoutSession", input, nil, &out, opts)
	return out, err
}

// CreateBillingPortalSession calls the management.createBillingPortalSession mutation.
// Create a hosted billing portal link where an organization manages its payment methods, invoices and subscription. The link grants access to whoever holds it; a retry with the same requestId returns the same link until it expires.
//
// Idempotency: singleUse. Like idempotent, but the result carries a short-lived credential for one connection. Request a new one instead of reusing an expired result.
// Retry budget: 3 attempts within 60 seconds.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) CreateBillingPortalSession(ctx context.Context, input CreateBillingPortalSessionRequestInput, opts ...CallOption) (*CreateBillingPortalSessionReply, error) {
	var out *CreateBillingPortalSessionReply
	err := c.t.call(ctx, "management.createBillingPortalSession", input, nil, &out, opts)
	return out, err
}

// ConfigureWebhook calls the management.configureWebhook mutation.
// Create a webhook endpoint for project events. The signing secret is delivered once through a credential delivery.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Long-running: poll [ManagementClient.GetOperation] with the operation reference from the result until the work completes.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) ConfigureWebhook(ctx context.Context, input ConfigureWebhookRequestInput, opts ...CallOption) (*ConfigureWebhookReply, error) {
	var out *ConfigureWebhookReply
	err := c.t.call(ctx, "management.configureWebhook", input, nil, &out, opts)
	return out, err
}

// UpdateWebhook calls the management.updateWebhook mutation.
// Change the event types of a webhook endpoint, or enable or disable it.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Long-running: poll [ManagementClient.GetOperation] with the operation reference from the result until the work completes.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) UpdateWebhook(ctx context.Context, input UpdateWebhookRequestInput, opts ...CallOption) (*UpdateWebhookReply, error) {
	var out *UpdateWebhookReply
	err := c.t.call(ctx, "management.updateWebhook", input, nil, &out, opts)
	return out, err
}

// RotateWebhookSecret calls the management.rotateWebhookSecret mutation.
// Start rotating the signing secret of a webhook endpoint. The next secret is delivered once through a credential delivery.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Long-running: poll [ManagementClient.GetOperation] with the operation reference from the result until the work completes.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) RotateWebhookSecret(ctx context.Context, input RotateWebhookSecretRequestInput, opts ...CallOption) (*RotateWebhookSecretReply, error) {
	var out *RotateWebhookSecretReply
	err := c.t.call(ctx, "management.rotateWebhookSecret", input, nil, &out, opts)
	return out, err
}

// DisableWebhook calls the management.disableWebhook mutation.
// Disable a webhook endpoint.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Long-running: poll [ManagementClient.GetOperation] with the operation reference from the result until the work completes.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) DisableWebhook(ctx context.Context, input DisableWebhookRequestInput, opts ...CallOption) (*DisableWebhookReply, error) {
	var out *DisableWebhookReply
	err := c.t.call(ctx, "management.disableWebhook", input, nil, &out, opts)
	return out, err
}

// ReplayWebhookDeliveries calls the management.replayWebhookDeliveries mutation.
// Redeliver one webhook delivery, or the deliveries of an endpoint in a time range, with their original event IDs.
//
// Idempotency: idempotent. Retry with the same requestId and identical input within the retry budget. The authority deduplicates by requestId; resolve an unknown outcome with resolveRequest.
// Retry budget: 3 attempts within 60 seconds.
// Long-running: poll [ManagementClient.GetOperation] with the operation reference from the result until the work completes.
// Authorized by portalCredential (condition: owner).
func (c *ManagementClient) ReplayWebhookDeliveries(ctx context.Context, input ReplayWebhookDeliveriesRequestInput, opts ...CallOption) (*ReplayWebhookDeliveriesReply, error) {
	var out *ReplayWebhookDeliveriesReply
	err := c.t.call(ctx, "management.replayWebhookDeliveries", input, nil, &out, opts)
	return out, err
}
