using Xunit;

namespace ConvoHop.Docgen.Tests;

public sealed class GeneratedTests
{
    private const string Header = "// <auto-generated>\n// Generated from a schema.\n// </auto-generated>\n#nullable enable\n";

    private const string Types = """
        namespace Lib
        {
            /// <summary>The Input input.</summary>
            public sealed class Input
            {
                /// <summary>Creates the input.</summary>
                /// <param name="id">The id.</param>
                public Input(string id) { Id = id; }

                /// <summary>The <c>id</c> field.</summary>
                public string Id { get; set; }

                /// <summary>The <c>limit</c> field.</summary>
                /// <remarks>Omitted when null.</remarks>
                [System.Obsolete("Use Size.")]
                public int? Limit { get; set; }

                /// <summary>The most items.</summary>
                public const int Max = 50;
            }

            /// <summary>The Role enum.</summary>
            public enum Role
            {
                /// <summary>The <c>SPEAKER</c> value.</summary>
                Speaker,

                /// <summary>The <c>LISTENER</c> value.</summary>
                [System.Obsolete]
                Listener,
            }

            /// <summary>The API.</summary>
            public class Api
            {
                /// <summary>Sends.</summary>
                public void Send() { }
            }

            /// <summary>An API with a name.</summary>
            public sealed class NamedApi : Api
            {
                /// <summary>The name.</summary>
                public string Name { get; } = "";
            }
        }
        """;

    [Fact]
    public void ShowsDataTypesOfGeneratedNamespacesAsStubs()
    {
        var package = Lib.Package(Header + Types);

        var input = Assert.Single(package.Symbols, symbol => symbol.Name == "Input");
        Assert.Equal("class", input.Kind);
        Assert.Equal("The Input input.", input.Docs);
        Assert.Null(input.Members);
        Assert.Equal(new[]
        {
            """
            public sealed class Input
            {
                public Input(string id);
                public string Id { get; set; }
                [Obsolete("Use Size.")]
                public int? Limit { get; set; }
                public const int Max = 50;
            }
            """,
        }, input.Signatures);

        var role = Assert.Single(package.Symbols, symbol => symbol.Name == "Role");
        Assert.Equal("enum", role.Kind);
        Assert.Null(role.Members);
        Assert.Equal(new[]
        {
            """
            public enum Role
            {
                Speaker = 0,
                [Obsolete]
                Listener = 1,
            }
            """,
        }, role.Signatures);
    }

    [Fact]
    public void ListsMembersOfGeneratedTypesWithMethods()
    {
        var package = Lib.Package(Header + Types);

        var api = Assert.Single(package.Symbols, symbol => symbol.Name == "Api");
        Assert.Equal(new[] { "public class Api" }, api.Signatures);
        Assert.Equal("Sends.", Lib.Member(api, "Send").Docs);
        var named = Assert.Single(package.Symbols, symbol => symbol.Name == "NamedApi");
        Assert.Equal(new[] { "public sealed class NamedApi : Api" }, named.Signatures);
        Assert.Equal("Api", Lib.Member(named, "Send").Inherited);
    }

    [Fact]
    public void ListsMembersOfGeneratedTypesNextToHandWrittenOnes()
    {
        var package = Lib.Package(Header + Types, """
            namespace Lib
            {
                /// <summary>A hand-written client.</summary>
                public sealed class Client { }
            }
            """);

        var input = Assert.Single(package.Symbols, symbol => symbol.Name == "Input");
        Assert.Equal(new[] { "public sealed class Input" }, input.Signatures);
        var limit = Lib.Member(input, "Limit");
        Assert.Equal(new[] { "public int? Limit { get; set; }" }, limit.Signatures);
        Assert.Equal("Use Size.", limit.Deprecated);
        Assert.StartsWith("The `limit` field.", limit.Docs);
    }

    [Theory]
    [InlineData("/* <autogenerated /> */\n")]
    [InlineData("// Copyright.\n// <auto-generated/>\n")]
    public void TakesAnyLeadingCommentWithTheMarker(string header)
    {
        var role = Assert.Single(Lib.Package(header + Types).Symbols, symbol => symbol.Name == "Role");
        Assert.Null(role.Members);
    }

    [Fact]
    public void TakesOnlyFilesThatBeginWithTheMarkerAsGenerated()
    {
        var late = Types.Replace("namespace Lib\n{", "namespace Lib\n{\n    // <auto-generated>");
        Assert.NotEqual(Types, late);
        var role = Assert.Single(Lib.Package(late).Symbols, symbol => symbol.Name == "Role");
        Assert.NotNull(role.Members);

        var partial = Lib.Package(Header + """
            namespace Lib
            {
                /// <summary>The Input input.</summary>
                public sealed partial class Input
                {
                    /// <summary>The <c>id</c> field.</summary>
                    public string Id { get; set; } = "";
                }
            }
            """, """
            namespace Lib
            {
                public sealed partial class Input
                {
                    /// <summary>The note.</summary>
                    public string Note { get; set; } = "";
                }
            }
            """);
        Assert.NotNull(Assert.Single(partial.Symbols).Members);
    }
}
